// Reviewed: ActorOps v2 Phase 2 is a default-off data plane; no route cutover, UI, or paid behavior changed.
import { codeHealthMaintenanceEntry } from './maintenanceChangelogEntries'
import { actorOpsPoolManagementChangelogEntries } from './actorOpsPoolManagementChangelogEntry'
import type { ChangelogMonth } from './changelogTypes'

export const changelogMonths: ChangelogMonth[] = [
  {
    id: 'month-2026-08',
    label: '2026 年 8 月',
    entries: [
      codeHealthMaintenanceEntry,
      ...actorOpsPoolManagementChangelogEntries,
      {
        date: '2026-08-13',
        title: '信息流刷新与收藏更及时、更可控',
        summary: '加载轮廓贴近真实卡片；获取范围按账户角色收口，并可在同一位置安全停止；收藏和长内容反馈同步更清楚。',
        items: [
          { title: '加载先看见真实结构', description: '硬刷新时，静态壳和应用内骨架都会保留头像、标题、摘要、分类和操作区轮廓，阅读列与卡片高度不跳动；减少动态效果时保持静态。' },
          { title: '获取范围与停止更明确', description: 'Member 只获取自己的私人订阅，Owner/Admin 还会获取自己订阅的公共来源，Viewer 不可启动。排队或运行中再次点击“获取新内容”会安全停止；已发出的调用完成后不会把结果写入信息流。' },
          { title: '阅读和收藏即时反馈', description: '时间流与专题速览的选中标识贴合图标；真实截断内容会显示可访问的展开/收起入口。收藏改为与侧栏一致的五角星，成功后进入收藏页立即能看到，失败仍会恢复原状态。' },
        ],
      },
      {
        date: '2026-08-12',
        title: 'ActorOps 可先恢复 X，并主动识别旧数据',
        summary: '严格候选不足时可由管理员明确启用单路兼容；来源水位、主备新鲜度、专用校验 Key 和统一诊断会阻止“旧帖子仍算成功”与重复失败校验。',
        items: [
          { title: '功能优先但费用仍需确认', description: '标准配置选择两个不同发布者的 Actor 即可启用，第三槽由管理员按需补充；严格方案仍凑不齐时会列出放宽项、保留底线和费用上限，可选择 1 个公开可运行候选。付费 Canary 与最终启用 1/3 兼容池仍分两次确认，旧池在此之前保持不变。' },
          { title: '单个合格候选不会被空搜索清掉', description: '兼容流程会跨免费搜索保留同一路线中每个 Actor 的最新安全证据；后续搜索没有新增候选或此前 3/3 验证已失败时，已合格的 1 个 Actor 仍可进入 Canary，不需要反复搜索。Actor 的 Build、Schema、价格或失败指纹变化后仍会重新判定。' },
          { title: '旧帖子不再冒充成功', description: '系统按每个来源的发布时间和稳定内容指纹维护水位；有新内容才增加成功计数，只有已见内容保持中性，结果倒退会立即切到备用。同一 Actor 连续三次只返回已见内容后，下一次正常周期会改用一个健康备用；当次不会额外启动付费 Actor，备用推进水位后成为该来源的后续首选。' },
          { title: '当前 Actor 可见且可以软切换', description: 'ActorOps 来源列表和详情会标记最近一次实际 Actor；可选择自动或一个首选 Actor，从下一次计划抓取起生效，不会因保存而立即产生费用。选择只改变本来源的调用顺序；首选旧数据、失败或暂停时仍自动切备，连续两次新鲜度通过后再恢复。' },
          { title: '降低要求入口恢复响应', description: '修复 X 选择单路兼容 Actor 后生成计划时缺少候选上限导致的服务端错误；兼容计划固定投影 1 个候选，失败也会在页面明确提示且不会启动 Actor。' },
          { title: '校验频率可设置', description: '可指定一个不参与生产的专用校验 Key，并按 Route 设置默认 24 小时、6–168 小时或关闭；启用/改频率和立即校验都会先展示单轮与理论月费用上限。' },
          { title: '失败会被记住', description: '同一 Actor 与 Build/Schema/价格指纹的确定性失败不会反复进入 AI 或付费计划；只有证据变化才会重新评估。已知中断 Run 只免费核对原状态；当前原审批批次优先于历史核对积压，若已终态失败，系统仅在证明版本号由中断保护步骤改变后继续同一审批中尚未运行的候选，并兼容旧 Worker 写入的零费用未运行项，不会重发失败 Actor 或跨越真实配置变更。' },
          { title: '三平台使用同一主备门槛', description: 'X、Instagram 和 YouTube 都要求两个不同发布者的实测 Actor，第三槽按需补充。YouTube 频道地址仅作身份，认证 Actor 未准备好时明确阻断，不回退 Atom/RSS 伪造成功。' },
          { title: '目标不匹配改为可理解提示', description: '当 Actor 返回其他账号或频道内容，或结果缺少可证明目标归属的字段时，页面会说明可能是推荐内容、默认账号、旧缓存或字段映射，不再只显示 target identity 技术错误码。' },
          { title: '诊断集中到一条时间线', description: '发现、验证、费用对账、切备、新鲜度、Key 与人工操作可按阶段和结果筛选；只显示公共 Actor 名称、安全原因码、次数和最终费用，不显示 Token、目标、正文或远端运行信息。' },
        ],
      },
      {
        date: '2026-08-11',
        title: '新增来源改为直接选择平台',
        summary: 'X、Instagram 和 YouTube 与其他来源同级展示；普通用户不再需要理解 Apify、Actor 或 Route，旧 X 池升级也只扩大安全检查范围。',
        items: [
          { title: '平台表单更直接', description: '新增来源可直接选择“X 账号”“Instagram 账号”或“YouTube 频道”。X 与 Instagram 只填写账号、获取条数和分析模式；页面移除 Actor Route、支持检查、Apify Key 和高级 JSON。' },
          { title: '暂不可用不会误导创建', description: '平台尚未就绪时仍可看到业务说明和管理员设置入口，但不会显示创建按钮；既有来源仍可维护名称、说明、频道和主题，目标与启用状态保持不变。' },
          { title: '旧来源保持兼容', description: '现有 X、Instagram 和 YouTube 来源不迁移、不改写也不停用；卡片、筛选和编辑统一显示平台名称。YouTube 始终优先使用公开 Atom Feed。' },
          { title: 'X 只升级当前三路', description: '免费检查直接核对当前三个 Actor，并把有效候选检查范围扩大到 30；安全、Schema、价格和发布者门槛不变。任一当前 Actor 不合格就保持原池，不自动换人或进入付费步骤。' },
          { title: '付费与生效继续分开确认', description: '只有当前三路都得到安全固定版本时才会显示逐项与总费用上限；付费验证和最终生效仍各自需要明确确认，未知启动只核对原运行。' },
        ],
      },
      {
        date: '2026-08-11',
        title: '助手连接命令可直接复制',
        summary: '创建连接时，一次性令牌、环境写入和 OpenClaw 配置命令都可直接复制，减少手动选择长命令的步骤。',
        items: [
          { title: '创建流程复制更紧凑', description: '一次性令牌与创建流程中的两段配置命令都使用带中文说明的图标按钮；令牌仅显示一行并省略末尾，复制内容保持完整。' },
          { title: '写入环境文件只需一次粘贴', description: '复制本地写入命令后，在终端粘贴运行即可创建或更新 ~/.openclaw/.env 中的 Inteliscope 令牌，保留其他环境变量并设置目录 0700、文件 0600。浏览器不会直接运行本机命令。' },
        ],
      },
      {
        date: '2026-08-11',
        title: '订阅统计可以直接查询对应内容',
        summary: '订阅卡右上角的今日、近 N 天和历史数量都会带你到该来源的对应结果，不必再手动设置来源筛选。',
        items: [
          { title: '今日与近 N 天直达信息流', description: '有内容时，点击今日会打开该来源的今日信息流，点击近 N 天会打开该来源当前 Feed 窗口内的内容；现有搜索和冲突筛选会被清除。' },
          { title: '历史入口保持不变', description: '历史数量继续直达该来源的历史列表，结果页会显示可清除的来源条件。' },
        ],
      },
      {
        date: '2026-08-11',
        title: '旧 UI 与历史发布链路完成退役',
        summary: '运行面收敛为 React、FastAPI、Worker 与 Remote MCP；旧接口和 writer 停止工作，同时保留现役 Feed、冷归档和历史数据安全边界。',
        items: [
          { title: 'React 成为唯一界面', description: '删除旧静态 UI、horizon-web 与构建缺失 fallback。React 产物缺失时 API 和 Remote MCP 仍可启动，页面明确返回 404；历史书签继续重定向到当前页面。' },
          { title: '运行服务只保留两项', description: 'Docker、Compose 与发布流程只运行 FastAPI 和 Worker；自动 Feed 与单源计划都由 Worker 执行，不再安装 CLI publisher、本地 MCP 或 scheduler。发布仍会阻断残留旧 scheduler 容器。' },
          { title: '旧分析接口明确下线', description: 'Archive analytics、Graph 与偏好反馈接口不再出现在 OpenAPI，访问时使用统一 404。Feed latest/history/search、存储治理冷归档、成员管理、来源总结、ActorOps 和 Remote MCP 保持不变。' },
          { title: '历史数据原样保留', description: '既有 data/site、horizon.db、旧 summaries、本地 MCP run 与 feedback 行不再被现役代码读取或改写，也不会由初始化或迁移删除；Fresh DB 不再创建 feedback 表。' },
          { title: '共享能力迁出 UI 命名空间', description: '认证、配置运行时、来源探测、Feed payload 与 Feed read 进入中性模块；Feed 读取强制使用 ServiceStore，杜绝静态文件和 ArticleStore 兜底。' },
        ],
      },
      {
        date: '2026-08-11',
        title: '信息流提示与深色状态更易辨认',
        summary: '新内容提示不再被顶部工具栏遮挡；深色模式下 Agent 面板的未配置与交接状态也保持可读。',
        items: [
          { title: '新内容提示保持可点击', description: '时间流和专题速览出现新内容时，按钮会固定在工具栏下方，避免被顶部操作覆盖；点击后仍会回到对应的新内容位置。' },
          { title: '深色状态对比度修复', description: 'Agent 面板的中性状态、已选上下文和交接说明提高了文本对比度，在深色主题与手机抽屉中都更容易辨认。' },
        ],
      },
      {
        date: '2026-08-10',
        title: '成员管理与专题总结同步更新',
        summary: '成员账号补齐安全改名和删除；来源级 AI 总结更聚焦，并可在当前浏览器恢复内容一致的最近结果。',
        items: [
          { title: '登录名可以维护', description: '非 Owner 成员行新增修改用户名操作；同工作区重名会保留弹窗并给出可修正提示，保存后新用户名立即用于后续登录。' },
          { title: '删除需要精确确认', description: '删除按钮会先打开确认框，只有输入该成员当前用户名后才允许提交；Owner 和管理员自己的当前账号保持受保护。' },
          { title: '运行与私人数据安全收尾', description: '账号删除会使会话失效并移除用户作用域数据，同时清空、停用遗留私人来源配置；仍有运行中任务时服务端会要求稍后重试。' },
          { title: '主线、变化与依据', description: '总结会合并重复内容、避免逐篇复述，关键要点用文章序号标出依据；样本不足时会明确提示，不补充 Feed 之外的事实。' },
          { title: '刷新后继续查看', description: '每个来源最近一次成功结果按账号隔离保留 30 天；仅当专题文章内容完全一致时恢复，标题和原始摘要不会写入浏览器缓存。' },
          { title: '查看不会重复计费', description: '收起状态显示“查看总结”，展开时才提供“重新总结”；查看缓存只展开已有结果，不会再次调用工作区 AI，明确退出后会清除。' },
          { title: '推理模型不再吞掉正文', description: '专题总结为隐藏推理预留输出空间；字符预算较小时会减少要点条数，避免显示半截单词或残句。空响应、截断或结构错误会保留真实失败和重试入口，不再用标题列表伪装成 AI 总结；日志也不会记录模型正文。' },
        ],
      },
      {
        date: '2026-08-10',
        title: 'ActorOps 优先升级原 Actor，来源不再反复卡死',
        summary: '兼容池的三个当前 Actor 始终排在候选最前；安全新版就绪后自动选中，不会再因候选不足被隐藏。',
        items: [
          { title: '当前 Actor 始终可见', description: '系统按主用和两个备用的顺序先列出当前 Actor；安全新版自动选中，未就绪的显示明确状态，替代者只用于失败缺口。' },
          { title: '防止重复免费检查', description: '候选排名和固定 Build 检查期间页面显示进行中，重复点击不会再创建同 Route 的 Discovery Job。' },
          { title: '来源失败前移', description: '兼容 Revision 没有固定 Build 时，来源页显示“先升级主备”并返回配置入口，不再创建注定失败的 Validation 或 Job，费用为 $0。' },
          { title: '顶部界面更轻', description: '抓取类型只显示产品名称，线路状态独立对齐；三项任务页签使用浅色强调底轨区分未选项，没有外框或阴影。' },
        ],
      },
      {
        date: '2026-08-10',
        title: 'Actor 验证可调参且不再原样重复付费',
        summary: '超时、空结果和状态读取失败现在有各自有效的下一步，相同失败与参数会在启动 Actor 前以 0 费用拒绝。',
        items: [
          { title: '超时可直接调整', description: '错误卡显示实际耗时与费用，新计划可把等待设为 180–900 秒，单次上限最高 $0.10；只提高费用不算有效修复。' },
          { title: '空结果不再误导', description: '运行已完成但 Dataset 为 0 时明确说明延长无效；只有 Manifest 支持时才显示 3/5 条样本，否则直接换 Actor。' },
          { title: '状态核对不二次启动', description: 'Run 或 Dataset 状态暂时读不到时，只重读已知运行，不会生成第二个 Actor POST；成功证据可继续原审批已包含的剩余验证。' },
          { title: '运行记录只告诉人怎么做', description: '内部成功任务继续隐藏；需要处理的失败显示原因、影响、下一步与返回 ActorOps，不提供付费通用重试。' },
        ],
      },
      {
        date: '2026-08-10',
        title: 'ActorOps 可以直接手选候选并补满三路',
        summary: '首次配置、旧版升级和第三路补位统一为候选手选、一次付费验证、一次确认生效，不再被内部流程或认证等待卡住。',
        items: [
          { title: '池成员由管理员决定', description: '首次配置和旧版升级从安全候选列表选择 3 个 Actor，补第三路选择 1 个；页面没有 Actor ID 粘贴框，版本与槽位仍由服务端安全固定。' },
          { title: '验证后即可运行', description: '固定 Build 的 Actor 通过付费验证后立即显示“已验证，可运行”并可确认生效；48 小时、参考来源和成功率认证转为后台观察，不再阻塞配置。' },
          { title: '旧线路全程不中断', description: '旧版池和现有两路会持续服务到新 Actor 与所有已启用来源验证完成；第二次确认才原子切换完整 3/3 或只补入备用 2。' },
          { title: '报错直接说明怎么处理', description: '失败统一显示原因、影响和下一步；运行记录隐藏成功的内部 Discovery/批次任务，付费失败只引导返回 ActorOps，不再展示原始 JSON 或通用重试。' },
        ],
      },
      {
        date: '2026-08-09',
        title: '专题速览与登录体验同步更新',
        summary: '信息流新增紧凑专题速览、来源级 AI 与 Agent 提问；登录页同步采用响应式 Quiet Studio 布局。',
        items: [
          { title: '宽屏品牌与表单分区', description: '桌面使用统一实色表面、细分隔线和语义排版呈现品牌信息与登录表单；手机自动堆叠并隐藏低优先级能力列表，不产生横向滚动。' },
          { title: '凭据输入更易确认', description: '用户名进入页面后自动聚焦，密码可以临时显示或隐藏；提交期间全部字段和动作锁定，避免重复登录请求。' },
          { title: '不扩大凭据存储范围', description: '页面不记住用户名、密码或密码显隐状态；每次提交都会清空并重新隐藏密码，登录接口与浏览器标准自动填充保持不变。' },
          { title: '按来源连续快速阅读', description: '专题速览在当前近 N 天窗口、搜索外的筛选结果和现有排序基础上按来源分组；来源按最近发布时间排序，组内继续沿用你的文章顺序，不会把多来源合并内容重复显示。' },
          { title: '紧凑时间线减少干扰', description: '每个来源使用一致的分组卡片，展开后仅以时间线显示标题、摘要和时间；专题模式移除逐篇标签、原文、收藏、Agent 和更多操作，详情与图片仍可按需展开。' },
          { title: '来源级总结与追问', description: '“AI 总结”继承工作区 AI 设置，只总结当前 Feed 已有文字而不访问网址；“问 Agent”附带最多 100 篇的只读专题快照，可继续编辑变化、脉络、风险与机会等问题。时间流、收藏、历史的完整操作不变。' },
          { title: '品牌图标随主题呈现', description: '浏览器标签和应用侧栏改用统一的双弧品牌图形；图标保持透明背景，并在浅色、深色环境中自动切换清晰的前景色。' },
        ],
      },
      {
        date: '2026-08-09',
        title: 'ActorOps 可引导补齐第三路并零中断升级旧配置',
        summary: 'ActorOps 收为三项任务流程；第三槽和旧版 Actor 都先旁路验证全部来源，再由第二次确认原子生效。',
        items: [
          { title: '每次只有一个下一步', description: '页面改为抓取类型选择器与“主备配置、来源启用、运行与告警”三个页签；免费搜索、付费验证和生效确认依次出现，不再要求理解 Route 表、机器状态或来源 ID。' },
          { title: '两路运行时安全补第三路', description: '主用与备用 1 正式认证后，可在不改变现有线路的情况下验证第三个不同 Actor 及全部已启用来源；第二次确认只把它加入备用 2。' },
          { title: '旧版配置旁路升级', description: '兼容 Actor 不会伪装成正式认证。系统在旧池持续服务时建立两个固定 Build 的新 Actor，来源验证完成后一次切换，历史 Revision 继续可审计。' },
          { title: '自动转正进度可见', description: '观察中的 Actor 已可运行；页面显示身份、参考来源、48 小时和成功率门槛，由系统自动认证，不提供误导性的手工转正操作。' },
        ],
      },
      {
        date: '2026-08-08',
        title: 'OpenClaw 输入区与对话起始建议更清晰',
        summary: 'Agent 输入区收为单层圆角边框并扩大可编辑空间；空对话新增可直接继续编辑的结构化建议。',
        items: [
          { title: '保留一层输入边框', description: '输入区移除顶部横线和文字框自身的边框、背景与阴影，仅保留外层圆角容器；左右留白缩小，让编辑区域更宽。' },
          { title: '更舒展的输入高度', description: '问题输入会在 80–180 px 内随内容增长，超出上限才在输入区内滚动；图片、模型、思考、发送和停止操作保持原位置与语义。' },
          { title: '对话从建议开始', description: '空对话显示三个带图标与说明的建议行。选择建议只会填入并聚焦问题输入框，不会自动发送或产生模型调用。' },
        ],
      },
      {
        date: '2026-08-07',
        title: 'VPS 发布流程缩短并可自动回滚',
        summary: '发布不再重复执行 main 与 Tag 的整套门禁，构建、CI 和传输可以并行，普通切换保留数据库备份、精确 revision 验证与自动回滚。',
        items: [
          { title: '精确复用 main 绿灯', description: '发布只接受与 origin/main 完全一致且已通过 Test Gate 的 SHA；main 绿灯后才创建 Tag，Tag 只验证同一 SHA 并追加隔离 API smoke，不再重复后端、前端和 UI 全套检查。' },
          { title: '耗时步骤并行执行', description: 'Linux 镜像构建与 main CI 同时进行，源包和镜像使用可恢复传输并行上传；UI E2E 也不再等待前端门禁结束。文档-only 变更不会启动无关的后端或前端作业。' },
          { title: '普通升级不再套用首次引导', description: '标准脚本直接升级现有 Service 数据库，不再要求空库 RC1 流程；发现迁移改动时会明确阻断并转入独立迁移手册。' },
          { title: '失败恢复与本地清理', description: '切换前在线备份 service.db 和环境文件，确认无活跃任务，并阻断仍在运行的历史 scheduler 容器；API、Worker、readiness、前端资源或公网 revision 任一失败都会恢复上一 release。发布结束后删除本次本地镜像，避免旧 build 持续堆积。' },
        ],
      },
      {
        date: '2026-08-07',
        title: 'OpenClaw 对话支持安全图片收发',
        summary: 'v2.2.13 的 Agent 输入框可选择、粘贴和拖放图片；对话历史使用 Gateway 的短期媒体票据恢复，不把图片交给 Inscope 服务保存。',
        items: [
          { title: '图片只在浏览器规范化', description: 'JPEG、PNG 和 WebP 会在当前页面重新编码、移除 EXIF 与原文件名，限制为每轮最多 4 张、单张 5 MiB、总计 12 MiB；纯图片消息不会把内部分析提示显示在对话中。' },
          { title: '只显示受信任媒体', description: '页面拒绝正文中的外链和本地文件 URL，只使用 Gateway 对会话、消息和内容块授权的 5 分钟媒体票据；刷新或重连会重新申请，图片元素不发送 Referer。' },
          { title: '兼容原版 Gateway 与云部署', description: '默认开关关闭。原版 Gateway 通过既有附件协议即可接收模型图片输入；只有安全显示 Gateway 输出/历史图片才需要 `chat.media.ticket`。云端只需配置 WSS/HTTPS Origin、共享媒体存储和票据密钥。' },
          { title: '发布基线与本地构建清理', description: '订阅页面的桌面、平板和手机明暗基线已与当前完整列表布局同步；每次本地服务健康验证成功后，重建流程只清理旧的 Inscope 本地镜像标签，当前镜像和仍被容器引用的镜像不会删除。' },
        ],
      },
      {
        date: '2026-08-07',
        title: '订阅工具栏会随滚动聚焦',
        summary: '订阅与来源库都以完整列表展示，搜索、筛选和新增来源在顶部保持同一操作面，并会随滚动收为透明胶囊，状态统计继续留在卡片右上。',
        items: [
          { title: '筛选取代侧边导航', description: '“我的订阅”和“来源库”都直接显示完整列表；需处理、公共和私人改由筛选完成，默认频道不再创建来源库导航。' },
          { title: '两态顶部工具栏', description: '页面顶部移除说明文字；初始工具栏以轻量圆角表面对齐来源卡内容，滚动后平滑收为居中胶囊。页签左侧保留，搜索居中，筛选和带文字的新增来源紧邻右侧；运行记录不显示来源工具。' },
          { title: '状态下方直接看条数', description: '今日、近 N 天和历史条数移到来源卡右上健康状态下方，底部集中保留更新摘要和操作。' },
        ],
      },
      {
        date: '2026-08-07',
        title: 'OpenClaw 附件与模型控件收紧',
        summary: '附件摘要现在使用统一满宽行、原位展开和快速清空；模型选择器也不会再挤占输入区。',
        items: [
          { title: '每条附件对齐右侧', description: '来源链接占满头像与移除按钮之间的可用空间，长标题安全截断，所有移除按钮固定在同一右边线。' },
          { title: '多条信息原位向上扩展', description: '超过两条附件时，包含“已附带 N 条 ↑”的整段摘要头控制原有容器向上柔和拉伸，箭头紧跟数量，仅显示尚未出现的附件，不复制前两条，也不打开新窗口。一至两条已全部显示时不出现入口。' },
          { title: '附件可一键移除', description: '右侧中性图标会立即清空全部附件，不需要确认，也不会清除已写的问题或发送消息。' },
          { title: '模型选择器更紧凑', description: '当前模型按内容宽度显示且最长 180 px；模型菜单最多 280×360 px，过多模型在菜单内部滚动，Provider 与模型能力信息保持可读。' },
        ],
      },
      {
        date: '2026-08-06',
        title: 'OpenClaw 原文分析与上下文引用优化',
        summary: '附带的信息现在会主动读取原文网址；来源引用使用订阅头像，并在原有摘要容器内完整查看。',
        items: [
          { title: '原网页读取透明降级', description: 'OpenClaw 先读取 Inscope 已保存内容，再访问同一条已清洗的原文网址；网页受限或不可读时会明确说明并仅分析已保存部分。' },
          { title: '来源更容易识别', description: '上下文引用优先显示受保护的订阅头像，缺少头像时继续使用来源图标；标题随可用空间自适应，长内容不会撑破面板。' },
          { title: '附件向上轻柔扩展', description: '向上箭头会让原有摘要容器向上拉伸，只显示未在摘要中出现的附件，保留键盘焦点、滚动和移除操作，并遵循减少动态效果设置。' },
        ],
      },
      {
        date: '2026-08-06',
        title: 'AI Key 成为连接主导配置',
        summary: 'AI Key 现在直接决定 Provider 和连接地址；工作区分析与触底文案分别绑定平级 Key 和模型。',
        items: [
          { title: 'Provider 不再是全局门槛', description: '工作区 AI 先选择 Key，再显示其 Provider；切换 Key 会按 Provider 填入默认模型，不再单独编辑 Provider。' },
          { title: '触底文案不再跟随或回退', description: '触底文案可选择所有已保存 AI Key 并保存自己的模型；保存后不受工作区 AI 开关、Provider、模型或地址影响，异常时安全保留内置文案。' },
          { title: 'AI 设置更紧凑', description: '两个 Key 字段支持按名称和 Provider 搜索，连接元数据收为次级信息；触底文案状态点击整条才展开三个场景的完整列表。' },
          { title: 'Apify Key 池卡片重排', description: '每个 Key 使用独立 HeroUI 卡片，状态固定右上角，额度以紧凑单行展示；检查、异常与安全操作直接呈现，不再需要打开详情。' },
        ],
      },
      {
        date: '2026-08-06',
        title: 'YouTube 频道头像恢复显示',
        summary: 'YouTube 频道会按已验证的频道 ID 取得头像并缓存为受保护的本地图片，信息流和订阅卡不再只显示 YT 占位。',
        items: [
          { title: '只读取固定公开页面', description: '头像只从已验证 UC Channel ID 对应的固定 YouTube 频道页有界读取，禁止跳转；图片仍经过公共网络、文件格式和大小校验后才进入本地媒体库。' },
          { title: '失败保持安全占位', description: '页面未提供头像、网络失败或图片校验失败时，不会改用通用 YouTube favicon 或外链图片，继续稳定显示 YT 占位。' },
        ],
      },
      {
        date: '2026-08-05',
        title: 'v2.2.10 设置概览卡片交互统一',
        summary: '设置概览与帮助入口点击整卡即可跳转，职责徽标固定到卡片右上角，移除迁移标记与箭头。',
        items: [
          { title: '帮助与版本整行可点', description: '操作手册、更新日志与 Release 发布页不再需要点小按钮，点击整行即可打开；外部发布页保留外链图标。' },
          { title: '卡片徽标与箭头归位', description: '工作区、管理员、只读与外观模式徽标统一固定在卡片右上角，「已迁移」标记与标题行箭头移除，卡片视觉更干净。' },
          { title: 'AI Key 连接地址真正独立', description: '工作区 AI 只选择 Provider、模型和 Key，不再编辑所谓全局 Base URL；每个 Key 在密钥页保存自己的连接地址，留空时使用 Provider 默认地址，触底文案与 Actor Discovery 也不会继承其他 Key 的地址。' },
        ],
      },
      {
        date: '2026-08-05',
        title: 'v2.2.9 触底文案 AI Key 绑定与工具栏透视',
        summary: '信息流触底文案可单独绑定同 Provider 的 AI Key，并使用该 Key 的独立连接地址；Feed 顶部工具栏改为半透明毛玻璃浮层。',
        items: [
          { title: '触底文案不再强绑工作区 AI Key', description: '“设置 → AI → 信息流触底文案”新增“生成用 AI Key”下拉，只显示与当前 Provider 匹配的已保存 Key；未选择时跟随工作区 Key，单独选择的 Key 使用自己的连接地址，地址为空则使用 Provider 默认地址。' },
          { title: '工具栏透明穿透且不遮挡内容', description: 'Feed 顶部工具栏改为 70% 半透明毛玻璃浮层，可透出后方内容；系统按实际工具栏高度动态避让列表、提示、加载和空态，筛选换行或移动端展开搜索时首张可见卡片不会被覆盖。' },
        ],
      },
      {
        date: '2026-08-05',
        title: 'v2.2.8 设置侧栏规格统一',
        summary: '设置工作区侧栏的宽度、内边距、字体与图标规格与主应用侧栏完全对齐，外观预览图比例同步修正。',
        items: [
          { title: '设置侧栏与主侧栏同规格', description: '设置侧栏宽度由 260px 统一为 232px，与主应用展开侧栏一致；导航项内边距、分组标签字号、图标尺寸与条目间距全部对齐主侧栏，移动端导航抽屉宽度同步调整。' },
          { title: '外观预览图比例一致', description: '浅色/深色主题预览中的微缩侧栏占比由 28% 修正为 20%，与设置工作区真实的侧栏与内容比例一致。' },
        ],
      },
      {
        date: '2026-08-04',
        title: 'v2.2.7 设置工作区发布验证修正',
        summary: '补强原生设置路由的发布验证与选择器退出态，保持现有业务、接口和信息流不变。',
        items: [
          { title: '设置路由验证更稳定', description: '历史链接跳转到“获取与主题”页后会等待原生页面完成挂载，再验证 RSS 首次抓取窗口的保存行为。' },
          { title: '选择器退出态保持可访问', description: '下拉菜单离场动画期间不再保留在可访问树中，避免瞬时低对比度内容影响辅助技术与无障碍检查。' },
        ],
      },
      {
        date: '2026-08-04',
        title: 'v2.2.6 设置工作区发布基线',
        summary: '独立 Settings Workspace 完成全部原生迁移；不改变 API、数据库或信息流侧栏。',
        items: [
          { title: '全部设置统一在独立工作区', description: '获取与主题、AI、密钥、ActorOps、存储与归档均使用独立路由和按页请求边界；历史链接会安全重定向。' },
          { title: '通知服务更易比较与管理', description: '服务状态、渠道和使用情况在响应式表格中集中显示，新增、编辑与归档保持原有 write-only 与确认语义。' },
        ],
      },
      {
        date: '2026-08-04',
        title: '设置工作区完成原生化收尾',
        summary: '存储与归档已迁入独立设置页，通知服务改为紧凑表格与弹窗管理，旧设置页面不再保留业务界面。',
        items: [
          { title: '存储与归档有了独立入口', description: 'Owner/Admin 可直接打开 `/settings/storage` 查看占用、预演清理与冷归档；归档批次使用紧凑表格，恢复和删除先在确认框中生成预演，原有精确确认与服务端指纹核对不变。' },
          { title: '通知服务改为表格管理', description: '桌面按服务、渠道、状态、使用情况和操作呈现；手机将次要信息合并到服务列。新增、编辑和归档均使用明确的弹窗，测试、启用和暂停收进每行“更多”菜单。' },
          { title: '历史链接继续可用', description: '旧 storage hash 和 `/settings/legacy` 会安全重定向到原生页面；无权访问的 Member/Viewer 回到概览且不请求管理员数据。' },
          { title: '设置视觉完成统一', description: '所有原生设置页继续采用实色中性表面、细边框、清晰状态和紧凑控件；不影响信息流侧栏或现有后端接口。' },
        ],
      },
      {
        date: '2026-08-04',
        title: 'ActorOps 迁入设置工作区',
        summary: 'Owner/Admin 现在可在独立 ActorOps 页面管理主备、发现、告警与事件；操作、权限和安全边界保持不变。',
        items: [
          { title: '独立路由与旧链接兼容', description: '新增 `/settings/actorops`，开发者分组顺序为“密钥、ActorOps、高级”。旧 ActorOps 书签会安全转到新页面，只有存储与归档继续保留在高级兼容页。' },
          { title: '桌面紧凑、手机无横向滚动', description: '桌面保留高密度路由表，手机改为信息明确的列表卡片；Revision、费用上限和 Discovery AI 细节默认折叠。' },
          { title: '查询只在需要时启动', description: '只有 Owner/Admin 打开 ActorOps 才读取对应数据；离开页面或收起 Discovery AI 后停止相关轮询与配置请求。' },
          { title: '设置视觉更清晰', description: '设置页面统一为实色中性层级、细边框和紧凑控件；密钥与获取/主题也同步收紧信息密度，不影响信息流视觉系统。' },
        ],
      },
      {
        date: '2026-08-04',
        title: '获取与主题迁入设置工作区',
        summary: 'Owner/Admin 现在可在独立“获取与主题”页配置 RSSHub、抓取窗口和阅读主题，保留原有保存与缓存语义。',
        items: [
          { title: '工作区导航更完整', description: '“来源”之后新增“获取与主题”；概览也提供对应入口。Member/Viewer 不显示入口，直接打开链接会安全回到概览。' },
          { title: '保存行为保持不变', description: 'RSSHub、获取窗口和主题可分别保存；多项修改仍通过同一原子配置请求保存，期间的新编辑不会被旧响应覆盖。' },
          { title: '旧链接继续可用', description: '旧 `#settings-fetching` 书签会转到 `/settings/fetching`。ActorOps 移至高级兼容页的 `#settings-actorops`，存储归档保持原入口。' },
        ],
      },
      {
        date: '2026-08-04',
        title: '密钥管理迁入设置工作区',
        summary: 'Owner/Admin 现在可在原生“密钥”页管理 AI Key 与 Apify 主备 Key 池，保留原有 SecretStore、权限和安全操作语义。',
        items: [
          { title: '密钥页不再打开旧设置', description: '新增 `/settings/secrets`，开发者分组内“密钥”排在“高级”前；AI 与概览的密钥入口也会直达原生页。旧密钥书签会自动转到新页面。' },
          { title: '真实值始终只写一次', description: '新增与轮换 Key 的真实值提交后立即清空，不会通过列表、提示、错误或缓存回显；失败时仍保留可安全编辑的元数据草稿。' },
          { title: 'Apify 池继续安全运行', description: '主备顺序、额度查询、排空、轮换和删除继续使用原有 API。额度保留五分钟缓存与刷新失败时的可信旧数据；运行中或排空中的 Key 必须先安全排空。' },
          { title: '权限和请求更收敛', description: 'Member/Viewer 看不到密钥入口；直接打开链接会回到概览，并且不会请求 Key、额度或 Apify 池数据。ActorOps 与存储归档仍在兼容设置页。' },
        ],
      },
      {
        date: '2026-08-03',
        title: '设置成为独立工作区',
        summary: '设置现在使用类似系统设置的独立侧栏与内容区，不再占用或改变信息流主侧栏；概览、外观、通知、AI 和已忽略内容均已原生化。',
        items: [
          { title: '返回原来的应用位置', description: '进入设置后左侧完整切换为设置导航，顶部“返回应用”会恢复打开前的页面、查询条件与定位；直接打开设置深链时安全回到信息流。' },
          { title: '设置导航按职责分组', description: '概览、来源、已忽略内容、AI、通知、外观与高级按工作区、智能、通信、系统和开发者分组；高级仅对 Owner/Admin 显示，本阶段不增加设置搜索。' },
          { title: '五个页面原生迁移', description: '概览以统一卡片呈现角色和入口，外观继续写入原有明暗偏好，通知完整复用既有服务与个人通知组件；AI 与已忽略内容也保持现有 API、缓存和写入语义，没有新增数据库或业务写入。' },
          { title: '手机使用全高设置侧栏', description: '小于 768 px 时内容全屏显示，顶部按钮打开与桌面相同的角色过滤 Drawer；选择页面后自动关闭，并保持无横向溢出。' },
          { title: '旧链接继续可用', description: '旧关于、通知、AI 与已忽略内容 hash 会转到对应原生页面；当时只有获取与主题、存储归档和密钥继续由兼容设置页承载，后续迁移保持原有权限、草稿与保存逻辑。' },
        ],
      },
      {
        date: '2026-08-03',
        title: 'YouTube Actor 不再因映射错误全军覆没',
        summary: '真实 Run 证明商城存在可返回完整视频字段的固定 Build；Discovery 现在使用正确频道 ID、Dataset 根路径和 Schema 优先证据。',
        items: [
          { title: '频道 ID 不再传错', description: 'Actor 输入字段为 channelId 或 channelIds 时使用已验证的 UC Channel ID，不再把频道 URL 或 handle 填入 ID 数组；公开参考频道同时保留 URL、handle 和稳定 UC ID。' },
          { title: '输出路径从真实根开始', description: 'Manifest 只从精确 Build Dataset row 根选择字段；若模型增加不存在的 candidate、item、data 或 result 包装，只有 Schema 能证明移除后路径精确存在时才安全修正。发布时间必须显式解析。' },
          { title: '完整视频 Schema 优先', description: '定价事件名仍用于淘汰明确的频道资料 Actor，但固定 Build 已证明视频 ID、视频 URL、发布时间和标题或正文时，不再被模糊的频道计费事件误杀；Store 的任意返回顺序也不再挤掉更强候选。' },
          { title: '旧候选可以继续补齐主备', description: '新一轮 Discovery 即使没有找到三个新候选，只要同 Route 仍有不同发布者的未试固定 Build，页面就会恢复“验证两路主备”，无需重复发现或提高价格。' },
          { title: '次数和费用按 Route 累计', description: '五次真实启动与 0.10 美元认证上限跨 Discovery Run 统一计算；换一轮补位不会重置预算，也不会重复试跑已消费候选。' },
          { title: '先复用、后发现', description: '批次只成功一路时先检查历史未试候选；能补齐就等待新的人工付费确认，确实没有可达方案时才创建不启动 Actor 的补位 Discovery。' },
          { title: '重复发现不再伪报系统错误', description: '同一个 Discovery Run 被并发排队时，先执行的任务负责推进状态，后执行的任务幂等结束，不再产生与实际候选失败无关的 ValueError。' },
          { title: 'Linux 发布基线同步', description: 'v2.2.1 将订阅能力目录的新布局同步到 Linux Chrome 的明暗主题移动端视觉基线；不改变 ActorOps 路由、费用、审批、运行逻辑或数据库迁移契约。' },
          { title: '已公开版本不改写', description: 'v2.2.0 标签保持原样，v2.2.1 作为可部署补丁版本修复发布验收。' },
        ],
      },
    ],
  },
  {
    id: 'month-2026-07',
    label: '2026 年 7 月',
    entries: [
      {
        date: '2026-07-31',
        title: '通知服务统一配置、测试并直接复用',
        summary: '管理员现在只在一个“通知服务”区域维护邮箱、Webhook 和 Telegram；个人新内容通知与 Apify 运行告警直接选择已经验证的服务。',
        items: [
          { title: '一次保存、测试并启用', description: '创建或修改服务只有一个“保存并测试”主操作；接收端确认成功后自动启用，失败会保留安全草稿供修改或重试。' },
          { title: '共享凭据就地复用', description: '首个 Telegram 服务同时填写 Bot Token 和 Chat ID，后续服务复用 Token；首个邮件服务同时填写 Provider 凭据和收件地址，后续服务复用发送凭据；Webhook 直接配置地址与可选签名。' },
          { title: '业务页面只选择服务', description: '个人通知和运行告警不再显示测试入口，可同时选择多个服务或多个相同渠道服务；暂停或不可用服务不能新选，但已有绑定仍可移除。' },
          { title: '兼容本机 fake-IP', description: 'Telegram 固定主机在解析到 198.18.0.0/15 时使用严格的应用内例外，仍强制 HTTPS、固定 Host/SNI、禁重定向和环境代理；不会读取或修改 Clash 配置，Webhook 仍拒绝 synthetic/private IP。' },
          { title: '保留 v16 身份与历史', description: '继续使用现有服务 ID、绑定、generation、水位与投递历史，不新增数据库迁移；历史私人目标不扩大共享范围，旧 API 继续兼容。' },
        ],
      },
      {
        date: '2026-07-30',
        title: '消息通知支持邮箱、Webhook 与 Telegram 多选',
        summary: '个人新内容通知和 Apify 运行告警都可同时启用多个渠道；每个渠道独立配置、测试和投递，切换时不再隐藏或清空邮箱配置。',
        items: [
          { title: '三张渠道卡始终可见', description: '邮箱、Webhook 和 Telegram 配置同时保留，可任意多选；每张卡显示自己的可用性、测试状态与发送结果，保存一种渠道不会清空另外两种。' },
          { title: 'Telegram 使用工作区共享 Bot', description: 'Owner/Admin 保存、测试并启用工作区 Bot Token；个人通知与运行告警分别使用自己的 write-only Chat ID，Token 和目的地均不会在页面、接口或日志中回显。' },
          { title: '失败隔离且不补发历史', description: '同一批新内容或同一运行告警会按渠道独立投递；一路失败不阻断其他渠道或抓取任务，服务恢复或重新启用后只发送之后严格新增的内容。' },
          { title: '旧客户端继续兼容', description: '旧版单渠道字段仍可读取和保存；新版多渠道字段提供逐渠道 generation、水位和测试状态，迁移会保留既有邮箱、Webhook 配置和投递历史。' },
        ],
      },
      {
        date: '2026-07-30',
        title: 'Actor 主备统一为三槽控制面',
        summary: 'X、YouTube 与 Instagram 共用 Route、不可变适配版本和来源级验证；Discovery 复用全局 AI，首期支持组合固定且不会误建 YouTube Profile。',
        items: [
          { title: '完整 2+1 优先、两路可先上线', description: '每条 Route 保留 Primary、Backup 1、Backup 2；完整认证池优先，但两个不同发布者的固定 Build 各成功一次 Canary 后即可降级上线，第三槽留空热补位，少于两路仍阻断。' },
          { title: 'Route 试跑一次确认', description: 'AI 只搜索公开 Actor、排序并生成受限 JSON Manifest；Route 认证由管理员核对服务端候选和批次上限后一次确认，来源级试跑、首次来源启用、新 Build 或新 Manifest 激活仍保持各自明确审批。同一次确认若因网络超时重放只返回原任务，不会再次扣费。' },
          { title: '新来源逐槽验证', description: '每个新账号或频道依次验证当前实际运行的两个或三个 Actor，全部确认身份并返回真实内容或可信空结果后才启用；只更换一个 Revision 时只重验对应槽。' },
          { title: '认证 Actor 优先', description: 'YouTube 仍保存为 RSS 来源，但来源 Canary 成功后先走认证 Actor；公开 Atom 仅在该次 Actor 失败时无费用降级，来源身份和稳定编号不变。' },
          { title: '人工选择工作区 AI Key', description: 'Actor Discovery 继承工作区 provider 与 model；管理员从同 Provider 的已登记 Key 中固定一个安全选项，并使用该 Key 自己的连接地址，下一次发现任务热生效，不另设模型配置，也不会自动换用其他 Key。' },
          { title: '可测量的输出容量', description: 'Discovery 单次 AI 超时提高至 180 秒；管理员可确认后顺序执行 YouTube/Instagram 32K 容量测试，安全查看 Token、耗时、finish reason 与 Manifest 校验，系统给出但不会自动采用生产上限建议。测试不会运行 Actor 或付费 Canary。' },
          { title: '候选不足不再归零', description: 'AI 一次排序并生成 3–6 个候选，系统逐项验证并让后序候选补位；已通过的 1/3 或 2/3 Revision 会保留展示，只有凑齐三个 Actor和两个发布者才开放付费 Canary。' },
          { title: '按内容类型召回 Actor', description: 'YouTube 发现精确搜索频道视频，Instagram 精确搜索账号帖子和 Feed，避免只抓账户资料的 Actor 挤占候选；模型会按当前有界目标返回完整排序备选，安全门槛与 0.02 美元上限不变。' },
          { title: '输入校验按候选隔离', description: '官方固定 Build 输入校验拒绝单个候选时会记录安全原因并继续验证后序 proposal；429、5xx、网络和解码错误只做三次有界重试，认证或请求合同错误才终止整次发现。' },
          { title: '输入模板不再依赖模型猜形状', description: '目标 URL、handle 或原生 ID 应放入 string、array 还是标准 startUrls object，由代码从公开 Build Schema 确定性生成；AI 复制安全模板并专注排序、输出映射和语义规则，无法映射的 Actor 在调用模型前淘汰。' },
          { title: '输出映射在付费前验真', description: 'Manifest 的每个 RFC 6901 路径都必须存在于精确 Build Dataset Schema；Profile/Channel 内容不能把帖子 URL 当作账号身份，账户资料型 Dataset 不再进入付费 Canary。' },
          { title: 'YouTube 元数据 Actor 不再消耗试跑', description: '频道资料、统计或主页字段不能再冒充视频条目；定价事件已明确只提供元数据的 Actor 会在 AI 前淘汰，某个固定 Build 已付费确认只返回元数据、占位或错误内容合同后也会永久关闭重复试跑入口。输出 Schema 不透明但已通过公开、固定 Build、权限、输入和费用门槛的频道 Actor 不由 AI 猜字段，只能经过一次受控观察 Canary；成功后才固化不可变映射并进入选择目录。' },
          { title: '混合 Dataset 不再误判失败', description: '时间转换支持有界 Unix 秒和毫秒；Actor 先返回账号元数据、后返回真实帖子时会隔离元数据行并继续验证内容，全为元数据才安全失败。' },
          { title: 'Canary 超时和费用可核对', description: '付费确认先显示 Route、来源、Actor、Build、商城价格和费用边界；Actor 默认最长等待 300 秒，超时中止且不自动重试，终态费用从远端账本回写。已有两路成功证据后不再为凑满第三槽继续付费。' },
          { title: '两路主备自动串行验证', description: '页面不再要求逐个候选点击。一次确认后，服务端最多选择三个不同 Actor 并逐项执行：每次付费启动前先免费核对公开 Actor 和精确 Build，两个不同发布者成功后立即停止，未启动候选费用为 0。' },
          { title: '候选用尽自动补位', description: '本批候选仍不足两路时会保留已经成功的证据，并自动创建一个不启动 Actor 的 Discovery 补位任务；未知启动结果仍会阻断整批、Route 与 Key，不会为了赶进度重复付费。' },
          { title: '批准上限不再冒充实际费用', description: '页面分别显示已终结实际费用与仍排队的批准上限。离线升级只把账本证明从未创建远端 Run/Dataset 的 start rejection 修复为 0 美元并停用失效 Build；不能证明未启动的旧记录继续显示费用未知。' },
          { title: '未知启动可以安全自愈', description: '启动请求结果未知时仍立即阻断且不切 Actor；系统等待安全窗后查询账号级 Run 列表，只有明确没有创建任何 Run 才记为 0 美元、归还试跑次数并恢复入口。系统不会自动重跑，下一次付费仍需重新确认。' },
          { title: '终态费用等待远端结算', description: 'Actor 终态后等待 Apify 费用聚合稳定并再次读取同一 Run；旧的过早费用记录会通过只读 GET 自动补账。页面将已确认实际费用、待对账笔数、尚未运行的批准上限和 0.10 美元认证预算分开显示，预算不是扣款。' },
          { title: 'v2.2.4 发布基线', description: 'v2.2.3 Tag 因发布文档门禁未通过而不部署、不改写；v2.2.4 同步版本、产品手册与 Changelog 后作为本次 YouTube Actor 热修的正式发布版本。' },
          { title: '未知启动时间窗恢复可用', description: 'v2.2.5 将 Apify 账号 Run 查询的起止时间固定序列化为接口接受的 UTC Z 格式，并把延迟对账窗口限定在原未知启动后的 30 秒安全边界；只读证明没有创建 Run 后会结算为 0 美元并解除 Route 与 Key 阻断，不会自动重跑。' },
          { title: '候选合格后只需确认启用', description: '页面不再暴露 Revision 下拉或手工排槽。服务端优先生成完整 2+1，也可生成两个 Canary 成功 Actor 的快速主备方案；管理员核对 Route、来源模式和费用上限后确认一次生效，浏览器不能指定候选。新来源按当前两或三路完成 2/2 或 3/3 验证。' },
          { title: 'Dataset 解码不重复付费', description: '所有 Apify 请求显式使用 identity encoding；已启动 X Run 的 Dataset 解码失败只会使用同一 Key 重读同一 Dataset，不会二次启动 Actor或切换槽位，耗尽后保留账本并安全阻断对账。' },
          { title: '支持组合固定', description: '首期支持检查只显示 X Profile、YouTube Channel 与 Instagram Profile 三种完整组合。离线升级会在确认没有候选、费用、绑定、验证或活跃任务证据后安全清理误建的 YouTube Profile，并保留合法 Route 的 generation 单调性。' },
          { title: '发现失败安全停止', description: 'Discovery Worker 的额度准入依赖已补齐；如果后续仍发生未处理异常，对应 Run 会与失败 Job 一起进入终态，不再保持 queued 并每轮重复补建任务。失败发生在 Store 或 AI 调用前时不会伪造查询、候选或可用度。' },
          { title: '配置无需重启', description: 'Actor、精确 Build、Manifest、三槽顺序和 Route 费用上限均带 generation 从 SQLite 热加载；新 Actor、Build 或 Manifest 仍需静态校验、付费 Canary 和管理员激活。运行中的任务冻结旧版本，过期结果不能写入新缓存或 Feed。' },
        ],
      },
      {
        date: '2026-07-30',
        title: '故障排查可以从请求串到后台结果',
        summary: '接口、后台任务、来源获取和通知现在使用同一组安全线索串联；管理员也可把工作区级脱敏诊断显式交给 OpenClaw。',
        items: [
          { title: '一个编号串联整次故障', description: '未知接口错误会返回可提供给维护者的请求编号；异步操作可继续按任务、来源和订阅关联排队、执行、逐来源结果与通知终态，不再依赖猜测时间点。' },
          { title: '日志写入失败可被发现', description: '服务会检查运行日志和操作事件是否真正写入；健康接口以独立状态提示日志降级，同时不会把已经成功的数据操作伪装成失败。' },
          { title: '工作区诊断必须显式授权', description: '连接默认仍只查看当前账户。Owner/Admin 新建连接时可选择工作区故障诊断；旧连接不自动提权，角色降级立即失效，查询只能按关联编号或 warning/error 收窄。' },
          { title: '后续开发自动受检', description: '新增写接口、后台任务类型或关键运行路径如果没有补齐日志合同，targeted、full 和 release 门禁都会失败；并行分支可继续开发，但合入最新基线时必须修正。' },
        ],
      },
      {
        date: '2026-07-30',
        title: '来源头像不再依赖新内容',
        summary: '来源账号即使本次没有新条目，也可独立取得、验证并缓存头像；订阅卡、信息流和 Agent 上下文会统一使用当前版本。',
        items: [
          { title: '零条目也能保留头像', description: 'RSS Feed 和社交账号响应会在时间窗口筛选前提取来源头像，Worker 在保存 Feed 前独立缓存，不再依赖“保留最新内容”制造一条内容记录。' },
          { title: 'B 站与免费来源有安全回退', description: 'B 站只接受与已保存 UID 精确匹配的公开搜索头像；GitHub、Reddit 和普通 RSS 可使用有界的免费账号信息或 favicon。回填不会调用 AI、通知、计划任务或付费 Actor。' },
          { title: '所有入口显示当前头像', description: '来源库、订阅、信息卡和 Agent 上下文只展示登录保护的本地图片；旧信息流会在读取时换成当前头像，缺失或加载失败则显示平台标识或来源简称。' },
        ],
      },
      {
        date: '2026-07-30',
        title: '设置分区随滚动自然加载',
        summary: '设置页的全部分区会在顺着页面阅读时依次显示正文，不再只留下标题卡片或要求返回区域选择器。',
        items: [
          { title: '七个分区统一生效', description: '关于、消息通知、助手与 AI、已忽略内容、获取与主题、存储与归档和密钥使用同一套相邻滚动激活逻辑；鼠标、触摸、键盘和滚动条都可自然进入下一分区。' },
          { title: '折叠页面也能继续', description: '多个折叠标题暂时同时落在一屏时，向下滚动会先加载相邻正文并恢复正常页面高度，不会因为没有新的相交回调而停在空卡片。' },
          { title: '按需读取仍保留', description: '首次进入分区才读取其数据，离开后保留缓存和未保存草稿并停止轮询；目录、手机端区域选择器与直接链接继续用于快速跳转。' },
        ],
      },
      {
        date: '2026-07-30',
        title: 'Webhook 通知适配七类常用接收端',
        summary: '个人新内容通知和 Apify 运行告警现在可显式选择通用事件、通用文本或五类平台机器人，并按接收端协议判断测试是否真正被接受。',
        items: [
          { title: '七类配置统一', description: '支持通用事件 JSON、通用文本 JSON、飞书/Lark V2、企业微信群机器人、钉钉、Slack/GovSlack 与 Discord；个人通知和工作区告警复用同一套类型、地址提示和验证规则。' },
          { title: '平台业务响应可验证', description: '飞书、企业微信、钉钉、Slack 和 Discord 不再只看 HTTP 状态，而会校验各自的成功响应；测试结果会明确区分“平台已接受”和“通用请求已发送”。' },
          { title: '飞书与钉钉支持签名', description: '机器人启用签名校验时可填写 write-only Secret；地址和签名提交后立即清空且永不回显，关闭签名会清除已保存的 Secret。通用类型仍是 URL-only，不增加 Bearer Token 或自定义请求头。' },
          { title: '失败不会伪装成功', description: '响应超限、格式异常或传输结果无法确认时会立即刷新并显示结果未知，明确要求先核对接收端且不自动重发；保存成功只表示配置已写入，不再等同于消息已经送达。' },
          { title: '旧配置平滑升级', description: '升级前的飞书地址继续按飞书格式发送，其他旧地址继续按通用事件发送；首次修改旧配置时需要显式选择类型并重新输入对应地址。' },
        ],
      },
      {
        date: '2026-07-29',
        title: '飞书 V2 Webhook 使用原生文本格式',
        summary: '账户新内容通知和 Apify 运行告警会识别未启用签名校验的飞书/Lark V2 自定义机器人地址，并发送群机器人可接受的文本消息。',
        items: [
          { title: '修复机器人消息协议', description: '此前通用 event/data 请求可能被飞书以 HTTP 成功、业务拒绝的方式静默丢弃；现在测试、真实新内容和运行告警都使用 msg_type/text 结构。' },
          { title: '通用 Webhook 保持兼容', description: '自建接收端和其他 HTTPS Webhook 继续收到原有结构化事件，不需要修改现有解析逻辑。' },
          { title: '明确实际送达边界', description: '保存成功只表示配置已写入，测试请求完成后仍要在接收端确认；签名校验暂不支持，关键词与 IP 白名单也必须匹配。' },
        ],
      },
      {
        date: '2026-07-29',
        title: 'X 抓取可在三路 Actor 间安全切换',
        summary: 'X 账号抓取只使用 Apify，并在低价 Actor 出现占位、故障或费用异常时串行切换；管理员可查看状态、费用、额度并选择邮件或 Webhook 告警。',
        items: [
          { title: '占位内容不会进入信息流', description: 'Demo、diagnostic、mock、付费墙和错误控制记录会在转换成帖子前被拦截；合法没有新帖仍算成功，不会误触发全局故障。' },
          { title: '三路串行主备', description: '初始顺序为 ScrapeBadger、Dami、Xquik；同一任务不会并行竞速。跨两个此前健康账号的系统性异常才熔断 Actor，单账号异常只暂停该订阅。' },
          { title: '恢复不额外花钱', description: '熔断后按 1、3、6、24 小时冷却，并复用自然任务探测；连续两次返回真实帖子才恢复，恢复后也不会自动抢回当前主路。' },
          { title: '费用有硬保护', description: '每次 Run 上限 0.02 美元、单个逻辑任务最多三路共 0.06 美元；任务重试复用原费用组，已成功 Dataset 只读重放。六小时失败消费达到 0.08 美元会暂停 X，并为其他 Apify 来源保留至少 1 美元或 20% 额度。' },
          { title: '状态与告警集中查看', description: '设置页显示三路健康、24 小时成功率和实际费用、冷却、额度及最近事故；运行告警采用首报、全挂升级和恢复各一次，可选工作区邮件或安全 HTTPS Webhook。' },
          { title: '付费试跑必须逐次确认', description: '每次 Canary 都要选择已启用的 X 来源并二次确认，且不会与同候选的自然任务并发；失败任务不能从通用重试入口再次扣费。页面与接口都不会返回 Token、目标账号或远端 Run/Dataset。' },
        ],
      },
      {
        date: '2026-07-29',
        title: '信息流末尾有了明确提示',
        summary: '信息流、收藏、历史和搜索结果只在真实最后一页显示终点，并可由管理员选择是否让 AI 定期更新安全短句。',
        items: [
          { title: '最终页才提示', description: '加载中、发生错误、仍有下一页或单字符搜索尚未提交时不会提前宣称触底；短列表一屏内结束时也能直接看到终点。' },
          { title: '末尾提示更轻', description: '终页和真实空列表都只显示一行“· 文案”，不再使用卡片、边框、大块底色或可见的大标题，也不会叠加两套空状态信息；短句可偶尔带一个克制 Emoji 或颜文字。' },
          { title: '收藏按页继续读取', description: '收藏改为每页 50 条的无限查询，并根据完整收藏数判断下一页；历史和搜索继续使用明确的“加载更多”。' },
          { title: '三类共享文案', description: '空列表、标签页会话首次触底和再次触底共用安全中文文案池；刷新保留会话次数，退出或关闭标签页后重置，连续触底避免紧邻重复。' },
          { title: 'AI 后台低优先级生成', description: '管理员可独立设置生成开关、周期、风格和数量；三个场景默认只显示条数，可分别展开完整文案列表并再次隐藏。立即刷新只标记待处理，Worker 在普通任务队列空闲后执行，失败保留上次成功或回退内置文案。' },
        ],
      },
      {
        date: '2026-07-29',
        title: '常用页面打开更快，后台列表更轻',
        summary: '首屏不再携带低频管理页面，信息流和运行记录也减少重复传输，同时保持原有功能、权限和刷新语义。',
        items: [
          { title: '低频页面按需加载', description: '订阅、Agent、设置、用户、手册和更新日志改为进入对应路由时才加载；登录、信息流、收藏和历史继续保持直接可用。' },
          { title: '首屏体积受门禁保护', description: '生产构建会校验六个低频路由仍为独立分包，并限制首屏 JavaScript 的 Brotli 合计体积，避免后续无意重新合并。' },
          { title: '信息流减少重复字段', description: '新版页面使用 canonical Feed，只传一份带时间分层的文章列表；兼容接口继续保留原有 today_items，旧调用方不受影响。' },
          { title: '运行记录先轻后详', description: '列表只读取展示所需的任务摘要，响应结构在展开时才读取完整详情；排队与运行中的任务仍保持原有实时轮询。' },
          { title: '稳定数据减少重复请求', description: '来源类型、设置、目录、Feed 和任务分别使用适合自身变化速度的短时缓存；手动重新载入、获取内容、深链定位和失败重试仍会按原语义刷新。' },
          { title: '订阅页不再重放历史任务', description: '跨页面只监控最近 20 条信息流相关任务，完整 100 条运行记录只在打开页签时读取；历史终态不会再触发成批取消、重复刷新或完成提示。' },
          { title: '设置分区打开后才读取', description: '隐藏分区不再抢占首屏请求；已打开分区保留缓存，但只有当前分区继续轮询。密钥分区首次打开仍会自动读取 Apify 额度，并缓存五分钟。' },
          { title: '条目操作不再扫描全部缓存', description: '收藏、已读、稍后读和忽略的乐观更新只处理当前账户中真正含内容条目的缓存，不再取消或重写订阅、任务、配置及其他账户数据。' },
          { title: '传输与静态路由更明确', description: '较大的合格响应支持 gzip；不存在的脚本、图片等文件路径返回 404，只有真实前端深链才回到应用页面。' },
        ],
      },
      {
        date: '2026-07-29',
        title: 'OpenClaw 可按名称订阅 YouTube 频道',
        summary: '只说频道名称即可由 OpenClaw 搜索官方主页、由 Inscope 验证频道身份并生成原有安全订阅预览，不再要求手工查 ID 或 RSS。',
        items: [
          { title: '通用解析入口', description: 'Remote MCP 新增一个注册表驱动的来源解析工具；首个适配器支持 YouTube，后续媒体只需增加受控适配器，不需要继续增加媒体专用 MCP 工具。' },
          { title: '名称由 Agent 发现', description: '只有名称时，OpenClaw 使用网页搜索收集最多 5 个官方 YouTube 频道主页；搜索结果视为不可信元数据，视频、播放列表、第三方和带凭据网址会在联网前被拒绝。' },
          { title: '官方身份双重验证', description: '服务先从固定 YouTube 频道页有界读取 Feed 链接，再读取官方 Atom Feed 核对频道 ID、名称和主页；网络仍只允许公开地址，不放宽内网、loopback 或任意 RSS。' },
          { title: '短期引用不泄露配置', description: '解析结果只返回频道名称、官方主页和 10 分钟有效的调用者绑定引用，不返回规范 Feed 或隐藏来源配置；已订阅频道不会生成重复创建引用。' },
          { title: '确认边界保持不变', description: '引用只能生成原有 prepare 预览，业务表在 apply 前不会改变；仍需用户逐字发送确认短语，最终来源统一保存规范频道 Feed 并保留最新一条。' },
        ],
      },
      {
        date: '2026-07-28',
        title: '全局与单源周期不再重复抓取',
        summary: '每个订阅默认跟随全局更新；启用单源独立周期后会自动退出全局任务，卡片也会显示真正生效的更新方式。',
        items: [
          { title: '默认跟随全局', description: '未配置单源周期的订阅统一使用页面上方“全局自动更新”；关闭全局时，来源卡会明确显示“跟随全局 · 全局已关闭”，不再误写成“手动更新”。' },
          { title: '单源周期互斥', description: '订阅设置使用带说明的互斥选项；选择“单源独立周期”后，该来源不再参与自动全局任务，避免两个计划紧邻重复抓取。' },
          { title: '切换不会丢周期', description: '切回“跟随全局（默认）”时保留上次单源周期；未来再次启用可直接复用。手动更新整个信息流仍会覆盖全部有效订阅。' },
          { title: '局部刷新保留内容', description: '自动全局任务只更新实际归属的来源，同时保留单源周期来源已有的信息流内容；全部来源都使用单源周期时，全局设置保留但不会创建空任务。' },
          { title: '卡片信息更准确', description: '来源卡用内联文字显示全局或单源周期与下次时间；订阅停用时只显示停用状态，手机端自然换行且不会增加横向滚动。' },
        ],
      },
      {
        date: '2026-07-28',
        title: '更新日志改为清晰时间线',
        summary: '版本记录按时间线与卡片重新组织，保留月份定位，并让长内容在桌面和手机上都更容易扫描。',
        items: [
          { title: '时间顺序更直观', description: '每条版本更新使用明确的节点和连接线，最新更新以强调节点标记，其余内容保持安静的时间顺序。' },
          { title: '内容层级更清楚', description: '日期、标题、摘要和详细改动分别落在低噪声卡片中；所有详情默认展开，较宽屏幕使用标题与说明双列，手机保持单列。' },
          { title: '导航与可访问性保留', description: '月份深链、键盘操作、滚动同步和响应式月份选择器继续可用；时间线使用有序列表语义，装饰轨道不会干扰辅助技术。' },
        ],
      },
      {
        date: '2026-07-28',
        title: '可直接订阅 YouTube 公开频道',
        summary: '频道链接、@handle、频道 ID 和规范 Feed 都会归一到同一来源，并继续复用现有订阅、获取、健康与通知流程。',
        items: [
          { title: '频道输入更灵活', description: '新增来源中提供“YouTube 频道”，支持公开频道链接、@handle、UC 开头的频道 ID 和规范 Feed 地址；不同写法不会重复创建同一频道。' },
          { title: '公开视频完整收录', description: '普通视频、Shorts、公开直播与回放都按频道公开 Feed 进入信息流，并统一显示为 YouTube 频道视频。' },
          { title: '首次只补一条', description: '默认开启“保留最新内容”；首次时间窗口为空时只保留最近一条，不会批量导入频道历史。' },
          { title: '无密钥安全解析', description: 'handle 仅通过固定 YouTube 公共页面进行一次有界解析，不使用 API Key、Cookie 或登录状态；失败会在创建弹窗中给出可操作提示且不会保存半成品来源。' },
          { title: '现有流程保持一致', description: '创建并订阅后不自动抓取；可继续使用“立即获取”、自动计划、来源健康和新内容通知。既有规范 YouTube RSS 会自动显示为 YouTube 频道。' },
        ],
      },
      {
        date: '2026-07-28',
        title: '本地任务分支重建流程已固定',
        summary: '同一条命令现在会从任务 Worktree 构建代码、复用主 checkout 的运行数据，并完成整条本地服务验收。',
        items: [
          { title: '代码与运行数据不再混淆', description: '从隔离 Worktree 执行重建时，版本、revision 和镜像来自当前任务分支，配置、数据库与日志仍使用主 checkout 的本地运行目录。' },
          { title: '完整可用才算完成', description: '镜像构建后会继续重建 API 与 Worker，并验证 revision、readiness、容器健康状态和实际前端资源；不会再把 build 成功误报为配置端口上的服务已启动。' },
          { title: '迁移仍需显式确认', description: '检测到数据库迁移时会先确认 API 与 Worker 已停止；已识别迁移会给出带备份的操作，未知迁移要求人工检查，不会自动改写运行数据。' },
        ],
      },
      {
        date: '2026-07-28',
        title: '卡片图片浏览更自然',
        summary: '有图卡片收起时即可看到一张轻量堆叠代表图，放大预览会在电脑与手机上完整容纳横图和竖图。',
        items: [
          { title: '收起即可查看代表图', description: '有图卡片会在正文右侧显示第一张可查看图片；点击直接打开放大预览，不会意外展开卡片。' },
          { title: '多图提示更轻', description: '两张及以上图片使用一至两层轻量背景表达堆叠关系，但只加载一张真实缩略图；无图卡片保持原有布局。' },
          { title: '竖图完整显示', description: '放大预览把主图与缩略图分开排布，横图和竖图都完整收在可见区域；多图仍可用缩略图、左右按钮、方向键或触摸滑动切换，单图不显示多余导航。' },
        ],
      },
      {
        date: '2026-07-27',
        title: '信息流按自然日分层并支持安全归档',
        summary: '工作区可选择近 7/14/30 天 Feed，旧内容保持可搜索，并新增预演优先的管理员存储中心。',
        items: [
          { title: '今天、Feed 与历史边界一致', description: '内容使用稳定展示时间和上海自然日划分；重复抓取不会把旧帖重新推回 Feed，修改窗口也不会抓取、建快照或删除数据。' },
          { title: '旧历史格式继续可读', description: '时间分层会为缺少新版展示结构的旧记录补齐安全字段；历史缓存即使仍含部分旧格式，也会回退到稳定标题、来源和分类，不再导致整页加载失败。' },
          { title: '搜索覆盖全部内容', description: 'Feed 顶部搜索会查询近 N 天、在线历史与冷归档元数据，按新到旧标记“今天 / 近N天 / 历史”；清除搜索后回到原 Feed 阅读位置。' },
          { title: '来源计数适配窗口', description: '订阅卡主行显示“今日 / 近N天 / 历史”，上次抓取数量移入更新时间和获取按钮说明；手机和中等宽度下自动重排。' },
          { title: '固定策略先预演再执行', description: 'Owner/Admin 可查看存储摘要并预演标准清理、90 日冷归档和恢复；候选变化会拒绝执行，归档校验失败不会删除在线数据。' },
          { title: '不会自动永久删除', description: '收藏、稍后读、当前 Feed 和待通知内容始终受保护；只有 Owner 能在归档已恢复且不再被引用后，用完整确认短语永久删除归档文件。' },
          { title: '发布启动不再下载依赖', description: 'API、Worker、调度器和旧版 Web 直接使用镜像内已安装的虚拟环境；发布门禁会断网验证 API 与 Worker 入口，VPS 重启不再临时解析或下载 Python 构建依赖。' },
        ],
      },
      {
        date: '2026-07-27',
        title: '低频来源的本地历史重新可达',
        summary: '旧内容没有丢失；历史页现在查询稳定内容索引，并把抓取量、当前量和历史量明确分开。',
        items: [
          { title: '超过快照窗口仍可查', description: '历史页不再只拼接最近 20 份信息流；来源条件和文本搜索会先覆盖当前账户的稳定内容，再分页返回并排除当前仍可见的 Feed 条目。' },
          { title: '来源计数不再混淆', description: '来源健康分别保存上次抓取、当前窗口和历史数量；历史大于零时可直接进入带可清除来源条件的历史页。' },
          { title: '旧帖不回填当前 Feed', description: 'X 和 Instagram profile 只有超窗旧帖时记录为成功抓取 0 条；来源保持健康，内容未变化时不生成重复快照，Facebook 与 Telegram 的既有行为保持。' },
          { title: '历史搜索与加载更多', description: '历史搜索使用防抖服务端查询，ViewBar 显示完整命中数；显式加载更多会稳定去重，失败时保留已经加载的卡片。' },
        ],
      },
      {
        date: '2026-07-27',
        title: 'OpenClaw、设置与订阅协作更顺畅',
        summary: 'Agent 不再强占阅读空间，核心配置可一次保存，订阅和信息流高频操作也更直接。',
        items: [
          { title: '隐藏后继续运行', description: '桌面端可在 OpenClaw 处理中关闭 Agent，连接、会话和生成继续运行；入口显示正在处理，完成、失败或停止后以明确图标、文字和顶部提示提醒，重新打开即可查看。移动端仍保留 Stop。' },
          { title: '概览按空间柔和避让', description: '固定 Agent 与信息概览在空间足够时同时显示；只有实测发生阻挡时才柔和关闭概览，不再一打开 Agent 就无条件收起。' },
          { title: '来源发送前后可追溯', description: '文章上下文会显示清洗后的原文来源，发送后仍保留在用户消息下方；链接移除跟踪与敏感参数，OpenClaw 仍先读取授权条目并把网页视为不可信内容。' },
          { title: '输入与运行控制更舒展', description: 'Agent 默认宽度提高到 400 px，输入区从 64 px 起随内容增长；transcript 是唯一主滚动区，短输入滚轮不再带出第二根滚动条或底部空白。模型按 Provider 分组，思考档位只显示精确模型能力，上下文用量统一用 k 展示。' },
          { title: '核心配置可一次保存', description: 'AI、RSSHub、抓取/筛选和主题库继续支持局部保存，也可从未保存提示一次原子提交；任一分区失败时不会保存其余分区，通知、邮件和 Key 保持独立安全流程。' },
          { title: '信息流工具栏更紧凑', description: 'Feed 增加独立搜索，排序口径、方向、重新载入、获取和筛选改为带完整说明的图标操作；ViewBar 说明优先向下显示，移动端可按需展开搜索。' },
          { title: '订阅范围更清楚', description: '“我的订阅”固定增加公共订阅和私人订阅，旧 workspace 来源归入公共；固定视图即使为零也保留，并与搜索和筛选后的结果计数一致。' },
          { title: '来源操作更直接', description: 'Pencil 从来源卡标题区移到下方紧凑控制行；私人来源所有者可直接分享，不再经过只有一个动作的“更多”，移动端控制行可安全换行。' },
        ],
      },
      {
        date: '2026-07-26',
        title: '状态更安静，中文输入不再误发',
        summary: '高密度状态和卡片操作改为图标与渐进披露，设置目录移到桌面侧栏，并修复 OpenClaw 中文输入法确认候选时提前发送。',
        items: [
          { title: '输入法 Enter 修复', description: '中文输入法仍在确认候选时，Enter 只完成输入，不会发送未写完的消息；普通 Enter 与 Shift+Enter 仍分别发送和换行。' },
          { title: '状态图标与说明', description: '来源健康、运行记录、自动更新、助手连接和 OpenClaw 顶栏只保留明确图标；鼠标停留或键盘聚焦时在上方显示完整说明，错误和运行轨迹仍保留文字。' },
          { title: '来源卡直接操作', description: '通知、订阅设置和编辑来源分别使用 Bell、Settings 和 Pencil 图标；订阅操作同处一行，取消订阅另有确认窗口；“更多”只在允许分享时出现，且只保留分享。' },
          { title: '连接危险操作收口', description: '复制、重命名、吊销或删除集中到中性“更多”菜单，并按连接状态裁剪；只有最终确认按钮使用红色实心样式。浏览器解绑也改为中性 Unplug 图标并保留二次确认。' },
          { title: '订阅统计迁入概览', description: '三个订阅页签不再长期显示数量；信息概览独立加载我的订阅、来源库和最近最多 100 条运行记录，读取失败不会闪成 0，点击可直达对应页签。' },
          { title: '桌面设置悬浮目录', description: '设置正文恢复单列；桌面从左侧“设置”悬浮或键盘聚焦打开分区目录，手机和触摸设备继续使用页内选择器，分区链接支持直接定位。' },
          { title: '后台健康判定更稳', description: 'Worker 健康检查为低配服务器留出完整启动探针时间，避免进程持续更新心跳时仍被误标为不可用。' },
        ],
      },
      {
        date: '2026-07-26',
        title: '等待过程可见，关键交互更可靠',
        summary: 'OpenClaw 会立即反馈运行过程，状态和元数据不再挤成相同胶囊，并补齐移动端、信息流、订阅与设置中的高频可用性缺口。',
        items: [
          { title: 'OpenClaw 运行轨迹', description: '发送后立即显示安全的处理中状态，并按需折叠展示读取、比较和工具步骤；原始思维、工具参数、结果和敏感值不会进入页面或历史。' },
          { title: '全部与异常视图', description: '我的订阅默认显示“全部”，并固定提供只包含需关注与连续失败的“异常”；即使暂时为零也可直接进入，移动端保持一致。' },
          { title: '来源操作分层', description: '编辑来源保持为直接图标，“更多操作”只在允许分享时出现；新内容通知仍在卡片直接切换，失败会恢复原状态，设置弹窗不再重复覆盖通知选择。' },
          { title: '获取按钮不再跳动', description: '“立即获取”在提交、排队和运行期间保持文字与宽度不变，以旋转图标、禁用状态和辅助技术文案表达进度。' },
          { title: '首次窗口可选', description: 'Owner/Admin 可把 RSS 首次抓取窗口设为 7 天或 30 天；新直接 RSS 与 RSSHub 来源首次成功后自动恢复日常窗口，抓到零条也视为成功。' },
          { title: '状态与元数据分型', description: '连接、运行和来源健康使用带辅助说明的状态图标；频道、主题、范围、权限和数量改用各自的轻量语义，不再共用微型胶囊。' },
          { title: '信息流交互补全', description: '“重新载入”和“获取新内容”明确分工；收藏与忽略提供 8 秒撤销，卡片菜单保持单实例并在关闭后归还焦点，多图支持缩略图、触摸切换和局部重试。' },
          { title: '移动端账户入口', description: '底部导航新增“更多与账户”，集中提供账户、设置、文档和退出入口，并适配系统安全区。' },
          { title: '加载与设置更稳', description: '自动更新检查不再闪现假失败；设置页提供分区导航、局部重试和未保存提醒，慢请求与局部错误不会遮挡整页。' },
        ],
      },
      {
        date: '2026-07-26',
        title: '浏览器 OpenClaw 可完成受控订阅',
        summary: '直接对话与文章/任务交接采用不同安全模式，创建订阅不再被只读提示词误拦截。',
        items: [
          { title: '直接请求可生成预览', description: 'Agent 面板没有附带文章或任务时，订阅请求会按用户原话交给 OpenClaw，并继续使用 Inscope Skill 与 MCP 的 prepare 流程。' },
          { title: '准确确认后才写入', description: '普通请求只展示安全预览与服务端返回的准确确认短语；只有下一条消息完全匹配该短语时才可 apply，浏览器不会替用户生成或改写。' },
          { title: '上下文交接仍只读', description: '附带文章或运行记录的分析继续只读取持久化安全证据，并禁止重试、取消、修复或其他写操作。' },
        ],
      },
      {
        date: '2026-07-25',
        title: 'Bilibili 订阅接入自建 RSSHub',
        summary: 'VPS 运行一套带访问控制的 RSSHub，本地与 VPS 项目可复用，并可在设置中切换到第三方实例。',
        items: [
          { title: '服务地址可切换', description: 'Owner/Admin 可在设置页维护 RSSHub Base URL；来源身份与服务地址分离，切换自建或第三方实例无需重建订阅。' },
          { title: 'OpenClaw 自行解析账号', description: '直接提供 Bilibili 账号名称即可通过 Inscope MCP 查询公开候选，无需启用 Chrome 或浏览器远程调试；唯一精确同名会解析为 UID 并进入订阅预览，同名多候选必须由用户选择，不再默认要求手工查 UID。' },
          { title: '查询数据严格收口', description: '名称查询只返回最多 5 个名称、UID、官方主页和精确匹配标记，不接收账号 Cookie，也不返回签名、粉丝数、视频数或上游正文。' },
          { title: 'Skill 自动刷新', description: '重新运行本地 OpenClaw 初始化会比较已安装 Skill 与仓库版本；发现旧版时覆盖更新并重启 Gateway，新会话不会继续沿用“手填 RSSHub URL”的旧规则。' },
          { title: '鉴权公网复用', description: 'RSSHub 容器只绑定 VPS loopback，由现有 Nginx 提供 HTTPS；本地直接访问公网入口，来源测试与 Worker 抓取使用路由级 code，主密钥不进入结果、日志或 OpenClaw。' },
          { title: '既有状态原位迁移', description: '精确匹配的 Bilibili URL 可原位转成受控路由，保留来源、订阅与自动更新计划 ID，并在写入前备份配置和数据库。' },
        ],
      },
      {
        date: '2026-07-25',
        title: '共享内容隔离与安全清理',
        summary: '共享来源继续复用已获取的正文，但每位成员只得到自己的订阅投影，媒体文件也只在数据库提交成功后清理。',
        items: [
          { title: '订阅偏好重新投影', description: '复用共享来源历史内容时，标题只采用独立保存的来源原始标题，频道、主题、个人标签、优先级和分析模式全部来自当前账户的目标订阅；缺少可信原始标题的旧内容不会预填，其他成员的 AI 翻译标题、偏好、精选状态和阅读状态也不会进入当前信息流。' },
          { title: '共享获取保持中性', description: '工作区级获取缓存只保留来源内容，写入前会清除生产者的 AI 结果和用户投影；缓存命中后再按当前订阅生成展示字段。' },
          { title: '媒体提交后清理', description: '过期内容的媒体数据库记录先随维护事务删除，文件只在提交成功后以尽力而为方式清理；SQL、提交或进程中断导致回滚时文件仍然保留。' },
          { title: '连接告警可观测', description: '完整测试门禁开始统计未关闭 SQLite 连接的 ResourceWarning，当前仅观测数量，便于后续持续收敛而不改变现有发布阈值。' },
        ],
      },
      {
        date: '2026-07-24',
        title: '侧栏弹出菜单更整齐',
        summary: '头像和文档入口保持原位，点击后出现的菜单收进侧栏范围。',
        items: [
          { title: '弹层内收', description: '账户菜单和文档菜单使用一致宽度，在展开侧栏内保留稳定的左右留白。' },
          { title: '入口保持原位', description: '头像、账户栏和右侧文档图标不移动，两个菜单继续从对应入口向上展开。' },
        ],
      },
      {
        date: '2026-07-24',
        title: 'OpenClaw 安全诊断事件',
        summary: '排查任务和关键操作时可以取得更连贯的脱敏事件，同时保持日志与账户严格隔离。',
        items: [
          { title: '按关联线索排查', description: 'OpenClaw 可在明确排障请求中按最近时间、任务、来源、订阅或请求关联查看安全事件，帮助串联排队、执行、获取和通知结果。' },
          { title: '只限当前账户', description: '只读与订阅管理连接都只能取得与当前账户相关的事件；Owner 或 Admin 连接也不能代查其他成员。' },
          { title: '原始日志不展示', description: '页面不新增日志列表或日志正文；原始消息、文件路径、身份、文章内容、URL、凭据和堆栈不会交给 OpenClaw。' },
          { title: '连接配置同步', description: '只读连接现在包含 11 个安全工具，订阅管理连接包含 15 个；原有 prepare、准确确认和 apply 边界不变。' },
        ],
      },
      {
        date: '2026-07-24',
        title: '信息流更新后立即呈现',
        summary: '后台获取完成后先载入最新信息流，以实际新增数量反馈结果，并提供稳定且不触发抓取的数据刷新入口。',
        items: [
          { title: '完成后再反馈', description: '整份更新或单个来源“立即获取”成功后，会先读取最新信息流，再显示去重合并后实际新增了多少条，避免总量已经变化而卡片仍停留在旧数据。' },
          { title: '刷新与更新分工', description: '信息流新增“刷新”按钮，只读取已有最新快照且所有成员可用，不会请求上游来源；加载期间文字和位置保持不变。原“更新”继续启动后台来源抓取，并遵循现有角色权限。' },
          { title: '失败时保留内容', description: '最新快照暂时加载失败时继续保留当前可信卡片，并提示回到信息流手动刷新，不会用空白或错误页替换阅读内容。' },
          { title: '阅读位置不跳动', description: '数据刷新和后台更新都会保留当前阅读锚点；离开新鲜边缘时，新到内容继续通过“N 条新内容”提示等待查看。' },
          { title: '常用控件更顺手', description: '外观按钮移到信息概览左侧；卡片使用明确的展开/折叠线框图标，底部操作说明优先显示在按钮上方。' },
        ],
      },
      {
        date: '2026-07-24',
        title: '订阅与运行记录更清爽',
        summary: '用更清楚的来源卡、筛选下拉和自动更新开关减少订阅页的信息拥挤。',
        items: [
          { title: '频道聚焦', description: '“我的订阅”和“来源库”分别记住当前频道；搜索或筛选使频道暂时无结果时，会自动回到首个有内容的频道，桌面选中标识也保持清晰对比。' },
          { title: '来源卡片', description: '来源卡只保留名称、类型、范围、HeroUI 健康状态标签、更新摘要和主操作；低频“查看引用”入口已移除，分享与编辑继续按权限放在明确的“更多”菜单。' },
          { title: '筛选与自动更新', description: '来源筛选改为原位下拉面板；全部订阅自动更新的纯开关固定在右上角，更新周期单独位于右下角，手机端也能直接操作。' },
          { title: '紧凑运行记录', description: '任务结果与创建、完成时间集中在一行展示；技术详情和响应结构通过带箭头、明确展开反馈的独立按钮按需显示。' },
        ],
      },
      {
        date: '2026-07-24',
        title: '主流邮件服务统一发件配置',
        summary: '由工作区管理员统一配置发件服务，成员只需填写自己的收件邮箱。',
        items: [
          { title: '五种服务商预设', description: '支持 QQ、网易、Gmail、Resend 与 Amazon SES；服务器、端口和 SSL 方式由系统固定派生，不开放任意 SMTP 地址。' },
          { title: '保存、测试、启用', description: '配置或凭据变化会自动停用；只有当前配置成功发送测试邮件后才能启用，凭据与测试收件人提交后立即清空且不回显。' },
          { title: '暂停不补发', description: '邮件服务未就绪时保留用户原有邮箱通知选择，但不会产生邮件队列；恢复后只通知之后真正新增的内容，Webhook 不受影响。' },
          { title: '凭据隔离', description: '授权码、App Password、API Key 与 SES SMTP Password 只写入 SecretStore；设置页和接口只显示安全配置状态。' },
        ],
      },
      {
        date: '2026-07-24',
        title: '偏好来源新内容通知',
        summary: '为明确选择的来源增加邮箱或 Webhook 主动通知，同时把历史数据留在信息流而不补推。',
        items: [
          { title: '账户接收方式', description: '每个账户可在设置页选择邮箱或 Webhook，保存后只显示是否已配置，并可发送一条不抓取来源的模拟测试通知。' },
          { title: '按来源开启', description: '订阅设置新增“从现在开始接收新内容通知”；开启后的来源卡片会显示通知状态。' },
          { title: '旧数据保护', description: '首次快照、历史或复用内容、停用期间的内容以及 personal_only 来源不会补推，只投递启用后确认的新条目。' },
          { title: '投递与获取隔离', description: '通知在信息流结果提交后独立发送；接收端失败不会让已经成功的来源获取被重复执行。' },
        ],
      },
      {
        date: '2026-07-24',
        title: '运行诊断与阅读细节完善',
        summary: 'OpenClaw 能取得更充分的安全任务证据，图片、概览和常用控件在窄空间下也更容易操作。',
        items: [
          { title: '运行记录直接诊断', description: '从运行记录加入 OpenClaw 后会读取安全的原因、证据和恢复建议，不再只停留在任务状态摘要，也不会自动重试或修改任务；窄屏上下文保持紧凑且不横向溢出。' },
          { title: '图片全图预览', description: '多图缩略格不再裁掉竖图；点击可查看完整图片，并通过左右按钮或方向键循环切换。' },
          { title: '更大的展开区域', description: '卡片使用图标式展开提示，标签和 Footer 空白也能展开；收藏、原文、Agent 与更多操作仍保持独立。' },
          { title: '概览先利用空白', description: '手动打开信息概览时，阅读列会先使用左侧空余空间让位，到达安全边界后才覆盖卡片。' },
          { title: '管理操作反馈', description: 'Apify 额度刷新会显示忙碌状态；OpenClaw 连接按钮保持同行，MCP 配置代码块也会对齐并安全换行。' },
        ],
      },
      {
        date: '2026-07-23',
        title: '操作手册与发布入口',
        summary: '把使用说明、产品更新和正式 Release 放到随时可达的账户区域，并建立合并文档门禁。',
        items: [
          { title: '操作手册', description: '新增源码受控的操作手册，覆盖订阅、阅读、运行记录、Agent、账户设置和常见状态排查。' },
          { title: '向上账户菜单', description: '侧栏底部头像菜单改为垂直向上展开；折叠导航也能直接进入操作手册、更新日志和 Release 发布页。' },
          { title: '文档与发布菜单', description: '展开侧栏后，账户右侧提供独立的向上菜单，可在操作手册、更新日志和 GitHub Release 页面之间选择。' },
          { title: '合并自动检查', description: '每次产品代码合并都由 Test Gate 验证操作手册与更新日志已同步复核，缺少任一项时检查失败。' },
        ],
      },
      {
        date: '2026-07-23',
        title: '操作结果不再挤压页面',
        summary: '保存、更新与任务结果统一从页面顶部短暂出现，正文和列表保持原位。',
        items: [
          { title: '顶部操作反馈', description: '设置、订阅、Agent、成员和 Feed 的操作结果会以可关闭提示短暂出现，不再推动页面内容。' },
          { title: '失败可直接重试', description: '刷新或来源任务失败且允许重试时，可直接在提示中重试；重复点击不会创建并行操作。' },
          { title: '表单仍在原位修正', description: '字段校验、弹窗内错误与排队或运行状态继续显示在对应控件附近，方便就地处理。' },
        ],
      },
      {
        date: '2026-07-22',
        title: '更清晰的交互反馈',
        summary: '让常用操作更靠近触发位置，状态变化更明确，工作区切换也更平稳。',
        items: [
          { title: '近邻提示', description: '鼠标与键盘触发的说明现在优先显示在控件右侧；空间不足时会自动换向或移动，异常详情也不再跑到页面角落。' },
          { title: '上下文选中态', description: '加入 Agent 上下文的按钮默认保持中性，仅在选中后显示紫色强调，并通过按压状态向辅助技术确认结果。' },
          { title: '柔和的工作区变化', description: '左右侧栏使用一致的短过渡；关闭 Agent 面板时先停止交互，再在动画结束后卸载内容。' },
          { title: '稳定的发送位置', description: 'OpenClaw 发送按钮切换为停止状态时保持在同一位置，连续操作不再引起工具栏跳动。' },
          { title: '可预期的信息流', description: '切换发布时间、入库时间或排序方向后，信息流会回到当前排序的新鲜边缘；筛选与刷新仍保留阅读位置。' },
          { title: '明确的明暗外观', description: '页头可以显式选择白天或黑夜模式；选择会在应用加载前恢复，不再被后续系统外观变化覆盖。' },
        ],
      },
      {
        date: '2026-07-22',
        title: '更新日志上线',
        summary: '产品内可以直接查看 Inscope 的重要体验变化。',
        items: [
          { title: '本地版本记录', description: '更新内容与代码一同维护，按月份组织；桌面端提供右侧时间线，窄屏使用横向月份选择器。' },
        ],
      },
    ],
  },
]

export const defaultChangelogMonthId = changelogMonths[0].id

export function isChangelogMonthId(value: string): value is ChangelogMonth['id'] {
  return changelogMonths.some((month) => month.id === value)
}
