import type { OpenClawArtifactDownload } from '../openclaw'
export const AGENT_ARTIFACT_PREVIEW_LIMIT = 2 * 1024 * 1024
export const AGENT_ARTIFACT_MEMORY_LIMIT = 50 * 1024 * 1024
const textMimeTypes = new Set(['application/json', 'application/typescript', 'application/javascript', 'application/x-javascript', 'text/markdown', 'text/plain', 'text/css', 'text/csv', 'text/javascript', 'text/typescript', 'text/x-python'])
function normalizedMime(value?: string): string { return (value ?? 'application/octet-stream').split(';', 1)[0].trim().toLowerCase() }
export function artifactPreviewKind(download: OpenClawArtifactDownload): 'image' | 'text' | 'download' { const mime = normalizedMime(download.artifact.mimeType); if (download.artifact.sizeBytes === undefined || download.artifact.sizeBytes > AGENT_ARTIFACT_PREVIEW_LIMIT) return 'download'; if (mime === 'image/svg+xml' || mime === 'text/html' || mime === 'application/xhtml+xml') return 'download'; if (mime.startsWith('image/')) return 'image'; if (textMimeTypes.has(mime) || mime.startsWith('text/x-')) return 'text'; return 'download' }
function gatewayHttpOrigin(gatewayUrl: string): string { const url = new URL(gatewayUrl); if (url.protocol === 'ws:') url.protocol = 'http:'; else if (url.protocol === 'wss:') url.protocol = 'https:'; if (url.protocol !== 'http:' && url.protocol !== 'https:') throw new Error('Gateway 地址无法映射到安全下载 origin。'); return url.origin }
export function validateArtifactTemporaryUrl(urlValue: string, expiresAt: string | undefined, gatewayUrl: string, now = Date.now()): string { const url = new URL(urlValue); if (url.protocol !== 'http:' && url.protocol !== 'https:') throw new Error('Gateway 返回了不安全的下载协议。'); if (url.origin !== gatewayHttpOrigin(gatewayUrl)) throw new Error('Gateway 临时下载地址不属于当前 Gateway origin。'); if (!expiresAt || !Number.isFinite(Date.parse(expiresAt)) || Date.parse(expiresAt) <= now) throw new Error('Gateway 临时下载地址已过期。'); return url.toString() }
function decodeBase64(value: string): Uint8Array { if (value.length > Math.ceil(AGENT_ARTIFACT_MEMORY_LIMIT / 3) * 4 + 4) throw new Error('产物超过 50 MiB 浏览器内存下载上限。'); const binary = atob(value); if (binary.length > AGENT_ARTIFACT_MEMORY_LIMIT) throw new Error('产物超过 50 MiB 浏览器内存下载上限。'); return Uint8Array.from(binary, (character) => character.charCodeAt(0)) }
export function artifactObjectUrl(download: OpenClawArtifactDownload, gatewayUrl: string): { url: string; revoke: () => void } { if (download.url) return { url: validateArtifactTemporaryUrl(download.url, download.expiresAt, gatewayUrl), revoke: () => undefined }; if (download.encoding !== 'base64' || !download.data) throw new Error('Gateway 没有返回可下载的产物内容。'); const bytes = decodeBase64(download.data); const body = new ArrayBuffer(bytes.byteLength); new Uint8Array(body).set(bytes); const url = URL.createObjectURL(new Blob([body], { type: normalizedMime(download.artifact.mimeType) })); return { url, revoke: () => URL.revokeObjectURL(url) } }
export function artifactPreviewObjectUrl(download: OpenClawArtifactDownload, gatewayUrl: string): { url: string; revoke: () => void } { if (artifactPreviewKind(download) !== 'image') throw new Error('该产物不支持安全图片预览。'); if (download.encoding === 'base64' && download.data && decodeBase64(download.data).byteLength > AGENT_ARTIFACT_PREVIEW_LIMIT) throw new Error('产物超过 2 MiB 预览上限。'); return artifactObjectUrl(download, gatewayUrl) }
export function artifactText(download: OpenClawArtifactDownload): string { if (artifactPreviewKind(download) !== 'text' || download.encoding !== 'base64' || !download.data) throw new Error('该产物不支持安全文本预览。'); const bytes = decodeBase64(download.data); if (bytes.byteLength > AGENT_ARTIFACT_PREVIEW_LIMIT) throw new Error('产物超过 2 MiB 预览上限。'); return new TextDecoder('utf-8', { fatal: true }).decode(bytes) }
export function triggerArtifactDownload(download: OpenClawArtifactDownload, gatewayUrl: string): void { const object = artifactObjectUrl(download, gatewayUrl); const link = document.createElement('a'); link.href = object.url; link.download = download.artifact.title; link.rel = 'noopener noreferrer'; link.click(); window.setTimeout(object.revoke, 0) }
