export const WORKBENCH_COLLAPSED_ROW_PX = 156
export const WORKBENCH_ROW_GAP_PX = 12
export const WORKBENCH_SKELETON_CARD_PX = WORKBENCH_COLLAPSED_ROW_PX - WORKBENCH_ROW_GAP_PX
export const WORKBENCH_EXPANDED_ROW_PX = 390
