"""Approved first-release information reminder limits."""
BATCH_WINDOW_SECONDS = 60
BATCH_ITEMS = 20
BATCH_INPUT_CHARACTERS = 32000
SEMANTIC_USER_CONCURRENCY = 1
SEMANTIC_USER_DAILY_BATCHES = 100
RULE_DAILY_NOTIFICATIONS = 20
