import AxeBuilder from '@axe-core/playwright'
import { expect, test, type Page } from '@playwright/test'
import { installShortcutFixture, shortcutRequests } from './fixtures/agent-shortcuts'

const dialogFastReminder = (page: Page) => page.getByRole('status').filter({ hasText: '更快消耗使用额度' })

async function resolvedThemeColor(locator: import('@playwright/test').Locator, token: string) {
  return locator.evaluate((node, token) => {
    const probe = document.createElement('span')
    probe.hidden = true; probe.style.color = `var(${token})`; node.append(probe)
    const color = getComputedStyle(probe).color
    probe.remove(); return color
  }, token)
}

async function expectCenteredEffort(page: Page) {
  const geometry = await page.locator('.effort-slider-track').evaluate((track) => {
    const bounds = track.getBoundingClientRect()
    const style = getComputedStyle(track)
    const inset = parseFloat(style.borderLeftWidth)
    const width = bounds.width - inset - parseFloat(style.borderRightWidth)
    const center = (node: Element) => { const box = node.getBoundingClientRect(); return { x: box.x + box.width / 2, y: box.y + box.height / 2 } }
    const marks = Array.from(track.querySelectorAll('.effort-slider-marks > span')).map(center)
    const index = Number(track.querySelector('input')?.value)
    return { bounds: { x: bounds.x, y: bounds.y, height: bounds.height }, inset, width, marks, index, thumb: center(track.querySelector('.effort-slider-thumb')!) }
  })
  expect(geometry.inset).toBe(geometry.bounds.height / 2)
  geometry.marks.forEach((mark, index) => {
    expect(Math.abs(mark.x - (geometry.bounds.x + geometry.inset + index * geometry.width / (geometry.marks.length - 1)))).toBeLessThan(.75)
    expect(Math.abs(mark.y - (geometry.bounds.y + geometry.bounds.height / 2))).toBeLessThan(.75)
  })
  expect(Math.abs(geometry.thumb.x - geometry.marks[geometry.index].x)).toBeLessThan(.75)
  expect(Math.abs(geometry.thumb.y - geometry.marks[geometry.index].y)).toBeLessThan(.75)
  const labelFits = await page.locator('.effort-model-trigger').evaluate((button) => {
    const bounds = button.getBoundingClientRect()
    return Array.from(button.children).every((child) => { const box = child.getBoundingClientRect(); return box.top >= bounds.top && box.bottom <= bounds.bottom + .5 })
  })
  expect(labelFits).toBe(true)
}

for (const theme of ['dark', 'light'] as const) test(`reference effort picker supports real levels and reset in ${theme}`, async ({ page }, testInfo) => {
  await installShortcutFixture(page, true)
  await page.addInitScript((theme) => localStorage.setItem('inteliscope.ui.theme.v1', JSON.stringify({ themeName: 'graphite-purple', colorMode: theme })), theme)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/agent')
  await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
  await page.getByLabel(/Gateway token 或 dashboard 地址/u).fill('fixture-token')
  await page.getByRole('button', { name: '连接并授权' }).click()
  const input = page.getByTestId('openclaw-composer-textarea')
  const sendButton = page.getByRole('button', { name: '发送给 OpenClaw', exact: true })
  await expect(sendButton).toBeDisabled()
  await expect(sendButton).toHaveCSS('opacity', '0.4')
  const sendAccent = await resolvedThemeColor(sendButton, '--accent')
  await expect(sendButton).toHaveCSS('background-color', sendAccent)
  const composerSurface = page.getByTestId('openclaw-composer')
  await expect(composerSurface).toHaveCSS('border-top-width', '0px')
  await input.fill('保留中文草稿')
  await input.click()
  await expect(input).toBeFocused()
  await expect(composerSurface).toHaveCSS('outline-style', 'none')
  await expect(composerSurface).toHaveCSS('outline-offset', '0px')
  await expect(composerSurface).toHaveCSS('box-shadow', 'none')
  await page.keyboard.press('Tab'); await page.keyboard.press('Shift+Tab')
  await expect(input).toBeFocused()
  await expect(composerSurface).toHaveCSS('outline-style', 'none')
  await expect(composerSurface).toHaveCSS('border-top-width', '0px')
  await page.screenshot({ path: testInfo.outputPath(`composer-focused-${theme}.png`) })
  const trigger = page.getByRole('button', { name: /OpenClaw 模型：/u })
  await expect(trigger.locator('.effort-toolbar-model')).toBeVisible()
  await expect(trigger.locator('.effort-toolbar-model')).toContainText('GPT Fixture')
  const context = await page.getByRole('button', { name: /上下文占用/u }).boundingBox()
  const send = await page.getByRole('button', { name: '发送给 OpenClaw', exact: true }).boundingBox()
  const control = await trigger.boundingBox()
  expect(context!.x + context!.width).toBeLessThanOrEqual(control!.x)
  expect(control!.x + control!.width).toBeLessThanOrEqual(send!.x)
  expect(send!.x - control!.x - control!.width).toBeLessThanOrEqual(8)
  await trigger.click()
  const themeAccent = await page.locator('.effort-picker-surface').evaluate((node) => { const style = getComputedStyle(node); return [style.getPropertyValue('--effort-accent').trim(), style.getPropertyValue('--accent').trim()] })
  expect(themeAccent[0]).toBe(themeAccent[1])
  const dialog = page.getByRole('dialog', { name: '模型与思考程度', exact: true })
  const fastButton = dialog.getByRole('button', { name: 'Fast 快速模式' })
  await page.mouse.move(0, 0)
  await expect(fastButton).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  if (testInfo.project.name !== 'mobile') {
    await fastButton.hover()
    const hoverColor = await resolvedThemeColor(fastButton, '--default')
    await expect(fastButton).toHaveCSS('background-color', hoverColor)
    await page.mouse.move(0, 0)
    await expect(fastButton).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  }
  const slider = dialog.getByRole('slider', { name: '思考程度' })
  await expect(slider).toHaveAttribute('aria-valuetext', '低')
  await expect(slider).toHaveAttribute('max', '5')
  await slider.focus(); await page.keyboard.press('End')
  await expect(slider).toHaveAttribute('aria-valuetext', 'Ultra')
  await dialog.getByRole('button', { name: '恢复默认思考' }).click()
  await expect(slider).toHaveAttribute('aria-valuetext', '低')
  await expectCenteredEffort(page)
  await slider.focus(); await page.keyboard.press('ArrowRight'); await expect(trigger).toHaveAccessibleName(/思考程度：中/u)
  await slider.focus(); await page.keyboard.press('ArrowRight'); await expect(trigger).toHaveAccessibleName(/思考程度：高/u)
  await expectCenteredEffort(page)
  await slider.focus(); await page.keyboard.press('End'); await expect(slider).toHaveAttribute('aria-valuetext', 'Ultra')
  await expectCenteredEffort(page)
  await page.keyboard.press('ArrowLeft'); await expect(slider).toHaveAttribute('aria-valuetext', '最高')
  await page.keyboard.press('ArrowLeft'); await expect(slider).toHaveAttribute('aria-valuetext', '很高')
  await page.keyboard.press('ArrowLeft'); await expect(slider).toHaveAttribute('aria-valuetext', '高')
  await expect(input).toHaveValue('保留中文草稿')
  const bounds = await dialog.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).analyze()).violations.filter((item) => ['serious', 'critical'].includes(item.impact ?? ''))).toEqual([])
  await page.mouse.move(0, 0)
  await expect(page.getByRole('tooltip')).not.toBeVisible()
  const composer = await page.getByTestId('openclaw-composer').boundingBox()
  const x = Math.min(bounds!.x, composer!.x)
  const y = Math.max(0, bounds!.y - 8)
  await page.screenshot({ path: testInfo.outputPath(`effort-${theme}.png`), clip: {
    x, y, width: Math.max(bounds!.x + bounds!.width, composer!.x + composer!.width) - x,
    height: Math.min(page.viewportSize()!.height, composer!.y + composer!.height + 8) - y,
  } })
  await dialog.getByRole('button', { name: /选择模型：/u }).click()
  await expect(dialog.getByRole('option', { name: /GPT Fixture/u })).toBeVisible()
  await page.keyboard.press('Escape'); await expect(trigger).toBeFocused()
  expect((await shortcutRequests(page)).filter((request) => request.method === 'chat.send')).toHaveLength(0)
})

test('only Fast decorates the slider and respects reduced motion', async ({ page }, testInfo) => {
  await installShortcutFixture(page, true)
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/agent')
  await page.getByLabel(/Gateway token 或 dashboard 地址/u).fill('fixture-token')
  await page.getByRole('button', { name: '连接并授权' }).click()
  const trigger = page.getByRole('button', { name: /OpenClaw 模型：/u })
  await trigger.click()
  const slider = page.getByRole('slider', { name: '思考程度' })
  await slider.focus()
  await page.keyboard.press('End')
  await expect(slider).toHaveAttribute('aria-valuetext', 'Ultra')
  const fast = page.getByRole('button', { name: 'Fast 快速模式' })
  await expect(fast).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('.effort-slider-sparks')).toHaveCount(0)
  await expect(page.locator('.effort-picker-surface')).not.toHaveAttribute('data-entering', 'true')
  await fast.focus()
  const fastTooltip = page.getByRole('tooltip')
  await expect(fastTooltip).toHaveText('Fast用量更多')
  await expect(fastTooltip).toHaveAttribute('data-placement', 'top')
  await expect(fastTooltip.locator('span').first()).toHaveCSS('font-size', '13px')
  await expect(fastTooltip.locator('span').first()).toHaveCSS('font-weight', '400')
  await expect(fastTooltip).toHaveCSS('opacity', '1')
  await expect(fastTooltip).not.toHaveAttribute('data-entering', 'true')
  await expect(page.locator('.effort-picker-surface')).toHaveCSS('opacity', '1')
  const tipBounds = await fastTooltip.boundingBox()
  expect(tipBounds!.y + tipBounds!.height).toBeLessThanOrEqual((await fast.boundingBox())!.y)
  const panelBounds = (await page.locator('.effort-picker-surface').boundingBox())!
  const captureX = Math.max(0, Math.min(tipBounds!.x, panelBounds.x) - 8)
  const captureY = Math.max(0, tipBounds!.y - 8)
  await page.screenshot({ path: testInfo.outputPath('fast-tooltip-above.png'), clip: { x: captureX, y: captureY, width: Math.min(page.viewportSize()!.width - captureX, panelBounds.x + panelBounds.width - captureX + 8), height: panelBounds.y + panelBounds.height - captureY + 8 } })
  await fast.click()
  await expect(dialogFastReminder(page)).toBeVisible()
  await expect(dialogFastReminder(page)).toBeHidden()
  await slider.focus()
  const spark = page.locator('.effort-slider-sparks i').first()
  await expect(spark).toHaveCSS('animation-name', 'effort-spark-drift')
  await expect(spark).toHaveCSS('animation-iteration-count', 'infinite')
  // Seek beyond the first cycle: Fast keeps moving without a wall-clock wait.
  const frames = await spark.evaluate((node) => {
    const animation = node.getAnimations()[0]
    animation.pause()
    return [5000, 6000, 9400].map((time) => {
      animation.currentTime = time
      const style = getComputedStyle(node)
      return { transform: style.transform, opacity: style.opacity }
    })
  })
  expect(frames[0]).not.toEqual(frames[1])
  expect(frames[0]).toEqual(frames[2])
  await expect(slider).toHaveAttribute('aria-valuetext', 'Ultra')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(spark).toHaveCSS('animation-name', 'none')
  const dialog = page.getByRole('dialog', { name: '模型与思考程度', exact: true })
  const bounds = await dialog.boundingBox()
  await page.mouse.move(0, 0)
  await page.screenshot({ path: testInfo.outputPath('effort-maximum.png'), clip: bounds! })
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(slider).toHaveAttribute('aria-valuetext', 'Ultra')
  await expect(spark).toHaveCSS('animation-name', 'none')
  await fast.click()
  await expect(slider).toHaveAttribute('aria-valuetext', 'Ultra')
  await slider.focus()
  await page.keyboard.press('Home')
  await expect(slider).toHaveAttribute('aria-valuetext', '低')
  await expect(page.locator('.effort-slider-sparks')).toHaveCount(0)
  expect((await shortcutRequests(page)).filter((request) => request.method === 'chat.send')).toHaveLength(0)
})

test('Fast switches the real send option independently and the thumb responds to hover', async ({ page }, testInfo) => {
  await installShortcutFixture(page, true)
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/agent')
  await page.getByLabel(/Gateway token 或 dashboard 地址/u).fill('fixture-token')
  await page.getByRole('button', { name: '连接并授权' }).click()
  const trigger = page.getByRole('button', { name: /OpenClaw 模型：/u })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: '模型与思考程度', exact: true })
  const fast = dialog.getByRole('button', { name: 'Fast 快速模式' })
  await expect(trigger.locator('.effort-toolbar-fast')).toHaveCount(0)
  await fast.click()
  await expect(fast).toHaveAttribute('aria-pressed', 'true')
  await expect(trigger.locator('.effort-toolbar-fast')).toBeVisible()
  await expect(trigger.locator('.effort-toolbar-fast')).toHaveCSS('rotate', 'none')
  await expect(trigger).toHaveAccessibleName(/Fast 已开启/u)
  const slider = dialog.getByRole('slider', { name: '思考程度' })
  await expect(slider).toHaveAttribute('aria-valuetext', '低')
  const thumb = dialog.locator('.effort-slider-thumb')
  await expect(thumb).toHaveCSS('box-shadow', 'none')
  if (testInfo.project.name !== 'mobile') {
    await thumb.hover()
    await expect(thumb).toHaveCSS('scale', '1.08')
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await expect(thumb).toHaveCSS('scale', '1')
  }
  const fastBounds = await fast.boundingBox()
  const modelBounds = await dialog.getByRole('button', { name: /选择模型/u }).boundingBox()
  expect(fastBounds!.x + fastBounds!.width).toBeLessThanOrEqual(modelBounds!.x)
  await page.keyboard.press('Escape')
  await page.getByTestId('openclaw-composer-textarea').fill('只验证 Fast 参数')
  await page.getByRole('button', { name: '发送给 OpenClaw', exact: true }).click()
  await expect.poll(async () => (await shortcutRequests(page)).filter((request) => request.method === 'chat.send').length).toBe(1)
  expect((await shortcutRequests(page)).find((request) => request.method === 'chat.send')?.params).toMatchObject({ fastMode: true, deliver: false })
})


test('connection actions align with fields at the reported width and 200 percent reflow', async ({ page }, testInfo) => {
  await installShortcutFixture(page, true)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/agent')
  for (const width of [900, 624, 320]) {
    await page.setViewportSize({ width, height: 889 })
    await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => resolve())))
    const actions = page.getByTestId('openclaw-setup-actions')
    await expect(actions).toBeVisible()
    const form = await actions.boundingBox()
    const first = await actions.getByRole('button', { name: '连接并授权' }).boundingBox()
    const second = await actions.getByRole('button', { name: '使用已配对设备重连' }).boundingBox()
    const field = await page.getByLabel('OpenClaw Gateway URL', { exact: true }).boundingBox()
    expect(Math.abs(form!.x - field!.x)).toBeLessThan(1)
    expect(Math.abs(form!.width - field!.width)).toBeLessThan(1)
    expect(Math.abs(first!.width - second!.width)).toBeLessThan(1)
    expect(Math.abs(first!.height - second!.height)).toBeLessThan(1)
    if (width < 640) {
      expect(first!.x).toBe(second!.x)
      expect(second!.y).toBeGreaterThanOrEqual(first!.y + first!.height + 8)
      expect(first!.width).toBe(form!.width)
    } else {
      expect(first!.y).toBe(second!.y)
      expect(second!.x + second!.width).toBe(form!.x + form!.width)
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`connection-${width}.png`) })
  }
})


test('entering Ultra reminds about tokens independently of Fast', async ({ page }) => {
  await installShortcutFixture(page, true)
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/agent')
  await page.getByLabel(/Gateway token 或 dashboard 地址/u).fill('fixture-token')
  await page.getByRole('button', { name: '连接并授权' }).click()
  await page.getByRole('button', { name: /OpenClaw 模型：/u }).click()
  const slider = page.getByRole('slider', { name: '思考程度' })
  const notice = page.getByRole('status').filter({ hasText: 'Ultra 会消耗更多 Token' })
  await slider.focus(); await page.keyboard.press('End')
  await expect(slider).toHaveAttribute('aria-valuetext', 'Ultra')
  await expect(notice).toBeVisible()
  await expect(notice).toHaveCSS('animation-name', 'effort-usage-reminder')
  await expect(page.getByRole('button', { name: 'Fast 快速模式' })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('.effort-slider-sparks')).toHaveCount(0)
  await expect(notice).toBeHidden()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.keyboard.press('Home'); await expect(slider).toHaveAttribute('aria-valuetext', '低')
  await page.keyboard.press('End'); await expect(notice).toBeVisible()
  await expect(notice).toHaveCSS('animation-name', 'none')
  await page.keyboard.press('Home'); await expect(notice).toBeHidden()
  expect((await shortcutRequests(page)).filter((request) => request.method === 'chat.send')).toHaveLength(0)
})
