import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'
import { installShortcutFixture, shortcutRequests } from './fixtures/agent-shortcuts'

test.beforeEach(async ({ page }) => {
  await installShortcutFixture(page)
  await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'dark' })
  await page.goto('/agent')
  await page.getByLabel(/Gateway token 或 dashboard 地址/u).fill('fixture-token')
  await page.getByRole('button', { name: '连接并授权' }).click()
  await expect(page.getByTestId('openclaw-composer-textarea')).toBeVisible()
})

test('advanced starters fill an editable task without sending it', async ({ page }, testInfo) => {
  const starters = page.getByLabel('进阶建议任务')
  await expect(starters.getByRole('button')).toHaveCount(3)
  await expect(page.getByRole('heading', { name: '让 Agent 深入分析' })).toBeVisible()
  await expect(page.getByRole('button', { name: '下一个建议' })).toHaveCount(0)
  const next = (await starters.locator('[data-position="right"]').boundingBox())!
  await page.mouse.click(next.x + next.width - 24, next.y + next.height / 2)
  await expect(page.getByRole('button', { name: '研判近期信号' })).toHaveAttribute('data-position', 'front')
  await expect(page.getByTestId('openclaw-composer-textarea')).toHaveValue('')
  await page.getByRole('button', { name: '研判近期信号' }).press('ArrowLeft')
  await expect(page.getByRole('button', { name: '排查采集链路' })).toHaveAttribute('data-position', 'front')
  await page.screenshot({ path: testInfo.outputPath('spatial-starters.png') })
  await page.getByRole('button', { name: '排查采集链路' }).click()
  const input = page.getByTestId('openclaw-composer-textarea')
  await expect(input).toBeFocused()
  await expect(input).toHaveValue(/按影响范围列出可能原因、证据和下一步/u)
  expect((await shortcutRequests(page)).filter((item) => item.method === 'chat.send')).toHaveLength(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).include('.prompt-suggestion').analyze()).violations).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('advanced-starters.png') })
})

test('spatial suggestions support swiping and light-theme motion', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference', colorScheme: 'light' })
  const stage = page.locator('.spatial-suggestions__cards')
  await stage.dispatchEvent('touchstart', { touches: [{ identifier: 1, clientX: 240, clientY: 300 }] })
  await stage.dispatchEvent('touchend', { changedTouches: [{ identifier: 1, clientX: 120, clientY: 305 }] })
  await expect(page.getByRole('button', { name: '研判近期信号' })).toHaveAttribute('data-position', 'front')
  await expect(page.getByTestId('openclaw-composer-textarea')).toHaveValue('')
  await page.getByRole('button', { name: '研判近期信号' }).press('ArrowRight')
  await expect(page.getByRole('button', { name: '优化订阅组合' })).toHaveAttribute('data-position', 'front')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).include('.prompt-suggestion').analyze()).violations).toEqual([])
})

test('card illumination reveals texture only under the pointer', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Fine pointer interaction')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  const card = page.getByRole('button', { name: '排查采集链路' })
  const texture = card.locator('.spatial-suggestions__texture')
  await expect(texture).toHaveCSS('opacity', '0')
  await card.hover({ position: { x: 100, y: 100 } })
  await expect(texture).toHaveCSS('opacity', '0.55')
  await page.screenshot({ path: testInfo.outputPath('card-light.png') })
  await page.getByRole('heading', { name: '让 Agent 深入分析' }).hover()
  await expect(texture).toHaveCSS('opacity', '0')
  await expect(page.getByTestId('openclaw-composer-textarea')).toHaveValue('')
})

test('advanced cards rotate while idle and pause during inspection', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'One browser is enough to verify the timer')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  const first = page.getByRole('button', { name: '排查采集链路' })
  const second = page.getByRole('button', { name: '研判近期信号' })
  await expect(first).toHaveAttribute('data-position', 'front')
  await expect(second).toHaveAttribute('data-position', 'front', { timeout: 6000 })
  await page.getByLabel('进阶建议任务').hover()
  await page.waitForTimeout(4700)
  await expect(second).toHaveAttribute('data-position', 'front')
  await expect(page.getByTestId('openclaw-composer-textarea')).toHaveValue('')
})

test('assistant Markdown renders as readable, safe content without mobile overflow', async ({ page }, testInfo) => {
  await page.evaluate(() => {
    ;(window as unknown as { shortcutFixture: { responseText: string } }).shortcutFixture.responseText =
      '## 🔴 高影响范围\n\n### 1. **Apple Developer News**\n- **状态**：`failing`\n- **证据**：持续失败 110 次\n\n| 来源 | 诊断 |\n| --- | --- |\n| Apple Developer News | UnsafeNetworkTarget-very-long-unbroken-diagnostic-identifier-for-mobile-layout |\n\n```text\nhttps://example.com/very-long-unbroken-path/that-must-wrap-inside-the-code-block-on-mobile\n```\n\n---\n\n[查看证据](https://example.com/log) [危险链接](javascript:alert(1)) ![外部图](https://example.com/image.png) <b>原文</b>'
  })
  await page.getByTestId('openclaw-composer-textarea').fill('诊断采集问题')
  await page.getByTestId('openclaw-composer-textarea').press('Enter')
  const answer = page.locator('[data-chat-role="assistant"] [data-chat-message-body]')
  await expect(answer.getByRole('heading', { name: '🔴 高影响范围' })).toBeVisible()
  await expect(answer.getByRole('heading', { name: '1. Apple Developer News' })).toBeVisible()
  await expect(answer.locator('li')).toHaveCount(2)
  await expect(answer.locator('li code')).toHaveText('failing')
  await expect(answer.locator('table')).toHaveCount(1)
  await expect(answer.locator('pre')).toContainText('very-long-unbroken-path')
  await expect(answer.locator('hr')).toHaveCount(1)
  await expect(answer.getByRole('link', { name: '查看证据' })).toHaveAttribute('rel', 'noopener noreferrer')
  await expect(answer.getByRole('link')).toHaveCount(1)
  await expect(answer.locator('img')).toHaveCount(0)
  await expect(answer).toContainText('<b>原文</b>')
  await expect(answer.locator('b')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).include('[data-chat-role="assistant"]').analyze()).violations).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('assistant-markdown.png') })
})

test('shared shortcut menu selects without sending and verifies Skill before chat.send', async ({ page }, testInfo) => {
  const input = page.getByTestId('openclaw-composer-textarea')
  await input.fill('/')
  await expect(page.getByRole('option', { name: /选择技能/u })).toBeVisible()
  await expect(page.getByText('快捷选择', { exact: true })).toHaveCount(0)
  const slashBounds = (await page.locator('.composer-suggestions').boundingBox())!
  expect(slashBounds.height).toBeLessThanOrEqual(330)
  await page.screenshot({ path: testInfo.outputPath('slash-menu.png') })
  await page.getByRole('heading', { name: '让 Agent 深入分析' }).click()
  await expect(page.locator('.composer-suggestions')).not.toBeVisible()
  await expect(input).toHaveValue('/')
  await input.fill('@天气')
  const option = page.getByRole('option', { name: /weather/u })
  await expect(option).toBeVisible()
  await expect(input).toBeFocused()
  const menu = await page.locator('.composer-suggestions').boundingBox()
  const composer = await page.getByTestId('openclaw-composer').boundingBox()
  expect(Math.abs(menu!.x - composer!.x)).toBeLessThanOrEqual(1)
  expect(Math.abs(menu!.width - composer!.width)).toBeLessThanOrEqual(1)
  expect(menu!.y + menu!.height).toBeLessThanOrEqual(composer!.y)
  await expect(option.locator('svg')).toBeVisible()
  const bounds = await option.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  expect(bounds!.height).toBeGreaterThanOrEqual(await page.evaluate(() => matchMedia('(pointer: coarse)').matches ? 44 : 32))
  expect((await new AxeBuilder({ page }).include('[data-testid="openclaw-composer-dock"]').include('[role="listbox"]').analyze()).violations).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('shortcut-menu.png') })
  await input.press('Enter')
  await expect(page.getByText('Skill：weather', { exact: true })).toBeVisible()
  expect((await shortcutRequests(page)).filter((item) => item.method === 'chat.send')).toHaveLength(0)
  await input.fill('检查天气')
  await input.press('Enter')
  await expect(page.getByText('模拟请求已完成')).toBeVisible()
  const requests = await shortcutRequests(page)
  expect(requests.filter((item) => item.method === 'skills.status')).toHaveLength(2)
  const sends = requests.filter((item) => item.method === 'chat.send')
  expect(sends).toHaveLength(1)
  expect(sends[0].params.message).toContain('\n$weather\n')
  expect(requests.some((item) => item.method === 'skills.run' || item.method === 'skills.update')).toBe(false)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('revoked Skill keeps the draft and never sends, while new cancellation does not create', async ({ page }) => {
  const input = page.getByTestId('openclaw-composer-textarea')
  await input.fill('@weather'); await expect(page.getByRole('option', { name: /weather/u })).toBeVisible(); await input.press('Enter')
  await page.evaluate(() => { (window as unknown as { shortcutFixture: { enabled: boolean } }).shortcutFixture.enabled = false })
  await input.fill('保留问题'); await input.press('Enter')
  await expect(page.getByText('无法确认本次 Skill 仍可调用。草稿已保留，请移除 Skill 或重试。')).toBeVisible()
  await expect(input).toHaveValue('保留问题')
  expect((await shortcutRequests(page)).filter((item) => item.method === 'chat.send')).toHaveLength(0)
  const before = (await shortcutRequests(page)).filter((item) => item.method === 'sessions.create').length
  await input.fill('保留问题 /new'); await input.press('Enter')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(input).toHaveValue('保留问题 ')
  expect((await shortcutRequests(page)).filter((item) => item.method === 'sessions.create')).toHaveLength(before)
})

test('Skills command floats above the composer without changing the conversation', async ({ page }, testInfo) => {
  const input = page.getByTestId('openclaw-composer-textarea')
  const timeline = page.getByTestId('openclaw-timeline')
  const initialTranscript = await timeline.textContent()
  const initialComposer = await page.getByTestId('openclaw-composer').boundingBox()
  await input.fill('保留草稿 /skills'); await input.press('Enter')
  const result = page.getByRole('region', { name: '/skills 命令结果' })
  await expect(result).toBeVisible()
  await expect(result.getByRole('button', { name: '使用 weather' })).toBeVisible()
  await expect(input).toHaveValue('保留草稿 ')
  await expect(input).toBeFocused()
  await expect(page.getByRole('listbox')).not.toBeVisible()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(timeline).toHaveText(initialTranscript ?? '')
  const panel = await page.locator('.composer-command-panel').boundingBox()
  const currentComposer = await page.getByTestId('openclaw-composer').boundingBox()
  expect(Math.abs(currentComposer!.y - initialComposer!.y)).toBeLessThanOrEqual(1)
  expect(Math.abs(panel!.width - currentComposer!.width)).toBeLessThanOrEqual(1)
  expect(panel!.y + panel!.height).toBeLessThanOrEqual(currentComposer!.y)
  expect((await new AxeBuilder({ page }).include('.composer-command-panel').include('[data-testid="openclaw-composer-dock"]').analyze()).violations).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('skills-command-output.png') })
  await page.getByRole('button', { name: '关闭快捷操作' }).click()
  await expect(result).not.toBeVisible()
  await expect(input).toBeFocused()
  await input.pressSequentially('/')
  await expect(page.getByRole('option', { name: /查看状态/u })).toBeVisible()
  await expect(page.getByRole('option', { name: /weather/u })).not.toBeVisible()
  await input.fill('/status'); await input.press('Enter')
  await expect(page.getByRole('region', { name: '/status 命令结果' })).toBeVisible()
  await expect(input).toHaveValue('')
  await page.getByRole('heading', { name: '让 Agent 深入分析' }).click()
  await expect(page.locator('.composer-command-panel')).not.toBeVisible()
  await expect(timeline).toHaveText(initialTranscript ?? '')
  expect((await shortcutRequests(page)).filter((item) => item.method === 'chat.send' || item.method === 'skills.update')).toHaveLength(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('local model, status and help commands keep chat idle', async ({ page }) => {
  const input = page.getByTestId('openclaw-composer-textarea')
  await input.fill('/model'); await input.press('Enter')
  await expect(page.getByRole('region', { name: '/model 命令结果' })).toContainText('GPT Fixture')
  await expect(page.getByRole('listbox')).not.toBeVisible()
  await page.keyboard.press('Escape')
  await input.fill('/status'); await input.press('Enter')
  await expect(page.getByRole('region', { name: '/status 命令结果' })).toContainText('当前对话状态')
  await input.fill('/help'); await input.press('Enter')
  await expect(page.getByRole('region', { name: '/help 命令结果' })).toContainText('快捷输入')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  expect((await shortcutRequests(page)).filter((item) => item.method === 'chat.send')).toHaveLength(0)
})

test('retired Worktree command cannot create or send a task', async ({ page }) => {
  const input = page.getByTestId('openclaw-composer-textarea')
  const before = (await shortcutRequests(page)).filter((item) => item.method === 'sessions.create').length
  await input.fill('/worktree'); await input.press('Escape'); await input.press('Enter')
  await expect(page.getByText('此工作区用于聊天与 Skill 调用，不提供 Worktree 任务。')).toBeVisible()
  expect((await shortcutRequests(page)).filter((item) => item.method === 'sessions.create')).toHaveLength(before)
  expect((await shortcutRequests(page)).filter((item) => item.method === 'chat.send')).toHaveLength(0)
})

test('Skill draft follows SPA switching into the narrow Feed rail and back', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'The fixed 320 px Feed rail is desktop-only')
  await page.evaluate(() => localStorage.setItem('inteliscope.ui.right-rail.v1:shortcuts', JSON.stringify({ width: 320 })))
  const input = page.getByTestId('openclaw-composer-textarea')
  await input.fill('@天气'); await expect(page.getByRole('option', { name: /weather/u })).toBeVisible(); await input.press('Enter')
  await input.fill('跨工作区草稿')
  const before = (await shortcutRequests(page)).filter((item) => item.method === 'connect').length
  await page.getByRole('button', { name: '切换工作区，当前为 OpenClaw' }).click()
  await page.getByRole('button', { name: 'Inscope 订阅、阅读与追踪' }).click()
  await page.getByRole('button', { name: '展开 Agent 面板' }).click()
  await expect(input).toHaveValue('跨工作区草稿')
  await expect(page.getByText('Skill：weather', { exact: true })).toBeVisible()
  const rail = page.getByRole('complementary', { name: 'OpenClaw 上下文' })
  const separator = page.getByRole('separator', { name: '调整信息流和 Agent 面板宽度' })
  await separator.focus(); await separator.press('Home')
  await input.fill('/')
  await expect(page.getByRole('listbox', { name: 'Agent 快捷候选' })).toBeVisible()
  expect(Math.round((await rail.boundingBox())!.width)).toBe(320)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await input.press('Enter')
  await expect(page.getByRole('region', { name: '/skills 命令结果' })).toBeVisible()
  await expect(page.getByRole('listbox')).not.toBeVisible()
  await input.fill('/')
  await expect(page.getByRole('option', { name: /新建对话/u })).toBeVisible()
  await expect(input).toBeFocused()
  await input.press('Escape')
  await page.getByRole('button', { name: '在 Agent 工作台打开' }).click()
  await expect(page.getByText('Skill：weather', { exact: true })).toBeVisible()
  expect((await shortcutRequests(page)).filter((item) => item.method === 'connect')).toHaveLength(before)
})

test('menu remains bounded in light theme and zoom-equivalent viewport', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Dedicated zoom and light-theme fixture')
  await page.getByRole('button', { name: '切换到白天模式' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.setViewportSize({ width: 720, height: 450 })
  await page.emulateMedia({ colorScheme: 'light', reducedMotion: 'reduce' })
  const input = page.getByTestId('openclaw-composer-textarea')
  await input.fill('/')
  const menu = page.getByRole('listbox', { name: 'Agent 快捷候选' })
  await expect(menu).toBeVisible()
  const box = await menu.boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(720)
  await expect(input).toBeFocused()
  expect((await new AxeBuilder({ page }).include('[data-testid="openclaw-composer-dock"]').include('[role="listbox"]').analyze()).violations).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('shortcut-light-zoom.png') })
})
