import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'
import { installShortcutFixture, shortcutRequests } from './fixtures/agent-shortcuts'

test.beforeEach(async ({ page }) => {
  await installShortcutFixture(page)
  await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'dark' })
  await page.goto('/agent')
  await page.getByLabel(/Gateway token 或 dashboard 地址/u).fill('fixture-token')
  await page.getByRole('button', { name: '连接并授权' }).click()
  await expect(page.getByTestId('openclaw-composer-textarea')).toBeVisible()
})

test('shared shortcut menu selects without sending and verifies Skill before chat.send', async ({ page }, testInfo) => {
  const input = page.getByTestId('openclaw-composer-textarea')
  await input.fill('@天气')
  const option = page.getByRole('option', { name: /weather/u })
  await expect(option).toBeVisible()
  await expect(input).toBeFocused()
  const bounds = await option.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  expect(bounds!.height).toBeGreaterThanOrEqual(44)
  expect((await new AxeBuilder({ page }).include('[data-testid="openclaw-composer-dock"]').include('[role="listbox"]').analyze()).violations).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('shortcut-menu.png') })
  await input.press('Enter')
  await expect(page.getByText('Skill：weather', { exact: true })).toBeVisible()
  expect((await shortcutRequests(page)).filter((item) => item.method === 'chat.send')).toHaveLength(0)
  await input.fill('检查天气')
  await input.press('Enter')
  await expect(page.getByText('模拟请求已完成')).toBeVisible()
  const requests = await shortcutRequests(page)
  expect(requests.filter((item) => item.method === 'skills.status')).toHaveLength(2)
  const sends = requests.filter((item) => item.method === 'chat.send')
  expect(sends).toHaveLength(1)
  expect(sends[0].params.message).toContain('\n$weather\n')
  expect(requests.some((item) => item.method === 'skills.run' || item.method === 'skills.update')).toBe(false)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('revoked Skill keeps the draft and never sends, while new cancellation does not create', async ({ page }) => {
  const input = page.getByTestId('openclaw-composer-textarea')
  await input.fill('/weather'); await expect(page.getByRole('option', { name: /weather/u })).toBeVisible(); await input.press('Enter')
  await page.evaluate(() => { (window as unknown as { shortcutFixture: { enabled: boolean } }).shortcutFixture.enabled = false })
  await input.fill('保留问题'); await input.press('Enter')
  await expect(page.getByText('无法确认本次 Skill 仍可调用。草稿已保留，请移除 Skill 或重试。')).toBeVisible()
  await expect(input).toHaveValue('保留问题')
  expect((await shortcutRequests(page)).filter((item) => item.method === 'chat.send')).toHaveLength(0)
  const before = (await shortcutRequests(page)).filter((item) => item.method === 'sessions.create').length
  await input.fill('保留问题 /new'); await input.press('Enter')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(input).toHaveValue('保留问题 ')
  expect((await shortcutRequests(page)).filter((item) => item.method === 'sessions.create')).toHaveLength(before)
})

test('local model, status and help commands keep chat idle', async ({ page }) => {
  const input = page.getByTestId('openclaw-composer-textarea')
  await input.fill('/model'); await input.press('Enter')
  await expect(page.getByRole('option', { name: /GPT Fixture/u })).toBeVisible()
  await page.keyboard.press('Escape')
  await input.fill('/status'); await input.press('Enter')
  await expect(page.getByRole('heading', { name: '当前对话状态' })).toBeVisible()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await input.fill('/help'); await input.press('Enter')
  await expect(page.getByRole('heading', { name: '快捷输入：@ 与 /' })).toBeVisible()
  expect((await shortcutRequests(page)).filter((item) => item.method === 'chat.send')).toHaveLength(0)
})

test('Worktree shortcut prefills the question but never creates before final confirmation', async ({ page }) => {
  const input = page.getByTestId('openclaw-composer-textarea')
  const before = (await shortcutRequests(page)).filter((item) => item.method === 'sessions.create').length
  await input.fill('补充登录测试 /worktree'); await input.press('Enter')
  await page.getByRole('button', { name: '这是独立信任域' }).click()
  await expect(page.getByRole('heading', { name: '在新 Worktree 中执行' })).not.toBeVisible()
  await input.fill('补充登录测试 /worktree'); await input.press('Enter')
  await expect(page.getByLabel('完整提示词')).toHaveValue('补充登录测试 ')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  expect((await shortcutRequests(page)).filter((item) => item.method === 'sessions.create')).toHaveLength(before)
})

test('Skill draft follows SPA switching into the narrow Feed rail and back', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'The fixed 320 px Feed rail is desktop-only')
  await page.evaluate(() => localStorage.setItem('inteliscope.ui.right-rail.v1:shortcuts', JSON.stringify({ width: 320 })))
  const input = page.getByTestId('openclaw-composer-textarea')
  await input.fill('@天气'); await expect(page.getByRole('option', { name: /weather/u })).toBeVisible(); await input.press('Enter')
  await input.fill('跨工作区草稿')
  const before = (await shortcutRequests(page)).filter((item) => item.method === 'connect').length
  await page.getByRole('button', { name: '切换工作区，当前为 OpenClaw' }).click()
  await page.getByRole('button', { name: 'Inscope 订阅、阅读与追踪' }).click()
  await page.getByRole('button', { name: '展开 Agent 面板' }).click()
  await expect(input).toHaveValue('跨工作区草稿')
  await expect(page.getByText('Skill：weather', { exact: true })).toBeVisible()
  const rail = page.getByRole('complementary', { name: 'OpenClaw 上下文' })
  const separator = page.getByRole('separator', { name: '调整信息流和 Agent 面板宽度' })
  await separator.focus(); await separator.press('Home')
  await input.fill('/')
  await expect(page.getByRole('listbox', { name: 'Agent 快捷候选' })).toBeVisible()
  expect(Math.round((await rail.boundingBox())!.width)).toBe(320)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await input.press('Escape')
  await page.getByRole('button', { name: '在 Agent 工作台打开' }).click()
  await expect(page.getByText('Skill：weather', { exact: true })).toBeVisible()
  expect((await shortcutRequests(page)).filter((item) => item.method === 'connect')).toHaveLength(before)
})

test('menu remains bounded in light theme and zoom-equivalent viewport', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Dedicated zoom and light-theme fixture')
  await page.getByRole('button', { name: '切换到白天模式' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.setViewportSize({ width: 720, height: 450 })
  await page.emulateMedia({ colorScheme: 'light', reducedMotion: 'reduce' })
  const input = page.getByTestId('openclaw-composer-textarea')
  await input.fill('/')
  const menu = page.getByRole('listbox', { name: 'Agent 快捷候选' })
  await expect(menu).toBeVisible()
  const box = await menu.boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(720)
  await expect(input).toBeFocused()
  expect((await new AxeBuilder({ page }).include('[data-testid="openclaw-composer-dock"]').include('[role="listbox"]').analyze()).violations).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('shortcut-light-zoom.png') })
})
