import AxeBuilder from '@axe-core/playwright'
import { expect, test, type Page } from '@playwright/test'
import { installAgentApi, installGatewayFixture } from './agentWorkspaceFixtures'

async function connect(page: Page) {
  await installAgentApi(page, true)
  await installGatewayFixture(page, true)
  await page.goto('/agent')
  await page.getByLabel(/Gateway token 或 dashboard 地址/u).fill('fixture-token')
  await page.getByRole('button', { name: '连接并授权' }).click()
  await expect(page.getByText('Gateway 已连接').first()).toBeAttached()
}

test('directory pages beyond 200, searches archives and restores the selected Agent', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'desktop exercises the directory protocol')
  await connect(page)
  const sidebar = page.locator('[data-agent-workspace-sidebar]')
  await expect(sidebar.locator('[data-agent-session-row]')).toHaveCount(3)
  await page.getByRole('button', { name: '全部会话', exact: true }).click()
  const history = page.getByRole('dialog', { name: '全部会话' })
  for (let pageIndex = 0; pageIndex < 4; pageIndex += 1) {
    await history.getByRole('button', { name: '下一页' }).click()
    await expect(history.getByRole('button', { name: `打开会话：历史记录 ${String((pageIndex + 1) * 50 - 1).padStart(3, '0')}`, exact: true })).toBeVisible()
  }
  await expect(history.getByRole('button', { name: '打开会话：历史记录 204', exact: true })).toBeVisible()
  await history.getByText('查看已归档会话', { exact: true }).click()
  await expect(history.getByRole('checkbox')).toBeChecked()
  await expect(history.getByRole('button', { name: '打开会话：归档记录' })).toBeVisible()
  await history.getByRole('checkbox').focus()
  await history.getByRole('checkbox').press('Space')
  await expect(history.getByRole('checkbox')).not.toBeChecked()
  await history.getByLabel('搜索会话').fill('历史记录 204')
  await expect(history.locator('[data-agent-session-row]')).toHaveCount(1)
  await history.getByRole('button', { name: '打开会话：历史记录 204', exact: true }).click()
  await expect(history).toBeHidden()
  await expect(page.getByRole('heading', { level: 1, name: '历史记录 204' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { level: 1, name: '历史记录 204' })).toBeVisible()
  const requests = await page.evaluate(() => (window as unknown as { __gatewayRequests: Array<{ method: string; params: Record<string, unknown> }> }).__gatewayRequests)
  expect(requests.find((request) => request.method === 'tools.effective')?.params).toMatchObject({ sessionKey: 'agent:research:dashboard:204', agentId: 'research' })
  expect(requests.filter((request) => ['sessions.create', 'chat.send'].includes(request.method))).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('directory-restored.png') })
})

test('async titles update in place and browsing does not widen resource scope', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'desktop exercises event and scope behavior')
  await connect(page)
  await page.evaluate(() => (window as unknown as { __renameSession: () => void }).__renameSession())
  await expect(page.getByRole('heading', { level: 1, name: '整理我的订阅' })).toBeVisible()
  await page.getByRole('button', { name: '全部会话', exact: true }).click()
  await page.getByRole('dialog', { name: '全部会话' }).getByLabel('搜索会话').fill('历史记录 204')
  await page.getByRole('dialog', { name: '全部会话' }).getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '打开Tasks' }).click()
  await expect(page.getByText('Fixture task')).toBeVisible()
  const scopes = await page.evaluate(() => (window as unknown as { __gatewayRequests: Array<{ method: string; params: Record<string, unknown> }> }).__gatewayRequests.filter((request) => request.method === 'tasks.list').map((request) => request.params.sessionKey))
  expect(scopes.length).toBeGreaterThan(0)
  expect(scopes.every((key) => key === 'root')).toBe(true)
})

test('compact composer, examples draft continuity and account menu work across viewports', async ({ page }, testInfo) => {
  await connect(page)
  const composer = page.getByTestId('openclaw-composer-textarea')
  const form = page.locator('.agent-workspace-composer')
  const size = await form.boundingBox()
  expect(size?.height).toBeLessThanOrEqual(testInfo.project.name === 'mobile' ? 140 : 128)
  const toolbar = page.getByTestId('openclaw-composer-toolbar')
  const model = await toolbar.getByRole('button', { name: /OpenClaw 模型/u }).boundingBox()
  const attachment = await toolbar.getByRole('button', { name: /附件|图片/u }).first().boundingBox()
  expect(model!.x).toBeGreaterThan(attachment!.x)
  await composer.fill('这段中文草稿需要保留')
  if (['mobile', 'compact-desktop'].includes(testInfo.project.name)) await page.getByRole('button', { name: '打开 OpenClaw 会话' }).click()
  await page.getByRole('link', { name: '使用示例', exact: true }).click()
  await expect(page).toHaveURL(/\/agent\/examples$/u)
  await page.goBack()
  await expect(composer).toHaveValue('这段中文草稿需要保留')
  await composer.fill(Array.from({ length: 30 }, (_, index) => `长输入第 ${index} 行`).join('\n'))
  expect(await composer.evaluate((element) => element.scrollHeight > element.clientHeight)).toBe(true)
  expect((await composer.boundingBox())!.height).toBeLessThanOrEqual(180)
  if (['mobile', 'compact-desktop'].includes(testInfo.project.name)) await page.getByRole('button', { name: '打开 OpenClaw 会话' }).click()
  await page.getByRole('button', { name: '打开账户菜单', exact: true }).click()
  await expect(page.getByRole('button', { name: '退出登录', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-account-menu-surface]')).not.toBeAttached()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  const results = await new AxeBuilder({ page }).analyze()
  expect(results.violations.filter((violation) => ['serious', 'critical'].includes(violation.impact ?? ''))).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('compact-composer.png') })
})

test('docked panels retain closing content, reverse smoothly and restore focus', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'docked panels require the wide layout')
  await connect(page)
  const trigger = page.getByRole('button', { name: '打开上下文' })
  await trigger.click()
  const panel = page.getByRole('complementary', { name: '上下文检查器' })
  await expect(panel).toHaveCSS('width', '360px')
  const close = panel.getByRole('button', { name: '关闭上下文', exact: true })
  await close.click()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(panel).toHaveCSS('width', '360px')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await close.click()
  await expect(page.locator('.disclosure-panel')).toHaveCSS('width', '0px')
  await expect(page.locator('.disclosure-panel')).toHaveAttribute('inert', '')
  await trigger.click()
  await expect(panel).toHaveCSS('transition-duration', '0s')
})


test('session menu confirms deletion and refreshes the sidebar and history', async ({ page }, testInfo) => {
  await connect(page)
  if (['mobile', 'compact-desktop'].includes(testInfo.project.name)) await page.getByRole('button', { name: '打开 OpenClaw 会话' }).click()
  const sidebar = page.locator('[data-agent-workspace-sidebar]')
  await sidebar.getByRole('button', { name: '会话详情：历史记录 000', exact: true }).click()
  await page.getByRole('button', { name: '删除会话', exact: true }).click()
  const confirmation = page.getByRole('dialog', { name: '删除会话', exact: true })
  await expect(confirmation).toBeVisible()
  await confirmation.getByRole('button', { name: '取消', exact: true }).click()
  await expect(confirmation).toBeHidden()
  await page.keyboard.press('Escape')
  await sidebar.getByRole('button', { name: '会话详情：历史记录 000', exact: true }).click()
  await page.getByRole('button', { name: '删除会话', exact: true }).click()
  await confirmation.getByRole('button', { name: '确认删除', exact: true }).click()
  await expect(confirmation).toBeHidden()
  await expect(sidebar.getByRole('button', { name: '打开会话：历史记录 000', exact: true })).toHaveCount(0)
  await sidebar.getByRole('button', { name: '全部会话', exact: true }).click()
  const history = page.getByRole('dialog', { name: '全部会话', exact: true })
  await history.getByLabel('搜索会话').fill('历史记录 000')
  await expect(history.getByText('没有匹配的会话')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})
